function setGraphNameCellArray=defMCADGraphName()
setGraphNameCellArray={'B Gap (on load)',
'PhaseCurrent1',
'PhaseCurrent2',
'PhaseCurrent3',
'PhaseCurrentD',
'PhaseCurrentQ',
'TorqueVW',
'TorqueVW_1',
'FluxLinkageLoadPh1',
'FluxLinkageLoadPh2',
'FluxLinkageLoadPh3',
'FluxLinkageLoadTotalD',
'FluxLinkageLoadPh1_1',
'FluxLinkageLoadPh2_1',
'FluxLinkageLoadPh3_1',
'TorqueMS',
'TorqueMS_1',
'FluxLinkageLoadTotalQ',
'FluxLinkageTorqueTotal',
'TerminalVoltage1',
'TemminalVoltage2',
'TerminalVoltage3',
'OnLoadEstimatedBackEMFPh1',
'OnLoadEstimatedBackEMFPh2',
'OnLoadEstimatedBackEMFPh3',
'TerminalVoltageA_1',
'TerminalVoltageB_1',
'TerminalVoltageC_1',
'ReluctanceTorque',
'AlignmentTorque',
'TorqueMSWW',
'TorqueMSWW_1',
'LineCurrent1',
'LineCurrent2',
'LineCurrent3',
'WindingFactors',
'WindingHarmonics_Mech',
'WindingHarmonics_Elec',
'TerminalLineToLine12',
'TemminalLineToLine23',
'TerminalLineToLine34',
'HarmonicAmplitude',
'HamonicAngle',
'HarmonicDataCycle',
'Flux DensityAirgap',
'FluxDensityAirgap_Br',
'FluxDensityAirgap_Bt',
'ACConductorLoss_Total',
'ACConductorLoss_Total_L',
'ACConductorLoss_Total_R',
'ACConductorLoss_L_1',
'ACConductorLoss_L_2',
'ACConductorLoss_L_3',
'ACConductorLoss_L_4',
'ACConductorLoss_R_1',
'ACConductorLoss_R_2',
'ACConductorLoss_R_3',
'ConductorFluxDensity_L_1',
'ConductorFluxDensity_L_2',
'ConductorFluxDensity_L_3',
'ConductorFluxDensity_L_4',
'ConductorFluxDensity_R_1',
'ConductorFluxDensity_R_2',
'ConductorFluxDensity_R_3',
'ConductorFluxDensity_R_4',
'Br Gap (on load)',
'Bt Gap (on load)',
'B Stator Tooth',
'B Stator Tooth Tip',
'B Stator Back Iron',
'B Rotor Back Iron',
};
end