function DisplaynameList=defHYBProxNameList()
DisplaynameList=...
{'P1DG1P',...
'P1DG2P',...
'P2DG1P',...
'P2DG2P',...
'P2DG1',...
'P2DG2',...
'PrectP',...
'P1DInstant',...
'PrectnonGamma',...
'PrectMCAD1D'};

end