function reNumberLayerTable=renumberCoilNumber(McadWindingPatternTable)
%% devfuncrenumberCoilNumber.mlx
reNumberLayerTable=McadWindingPatternTable;
reNumberLayerTable.CoilNumber=reNumberLayerTable.CoilNumber+1;
end