function [SolidGeomSetList,FaceGeomSetList]=mkGeomSetList4InnerRotor(PartName)
            if strcmp(PartName,'Rotor') ||strcmp(PartName,'Stator')   
                SolidGeomSetList={[PartName,' Core'] ...
                [PartName,' Core Front']...
                [PartName,' Core Middle']...
                [PartName,' Core Back']...    %% Face
                };
            else 
                %% Coil & Insulation & Magnet
                SolidGeomSetList={PartName ...
                [PartName,' Front']...
                [PartName,' Middle']...
                [PartName,' Back']...
                };
            end
        %% FaceGeomSetList  
            if  strcmp(PartName,'Stator') 
                FaceGeomSetList = {...
                [PartName,' Gap Face']...
                [PartName,' Core Side Face']...
                [PartName,' Core Front Face']...
                [PartName,' Core Back Face']...
                'Coil-Stator Core Face'
                };
            elseif strcmp(PartName,'Rotor') 
                FaceGeomSetList={...
                [PartName,' Gap Face']...
                [PartName,' Front Face']...
                [PartName,' Back Face']...
                [PartName,' Core-Shaft Face']...
                };
            elseif strcmp(PartName,'Coil') 
                FaceGeomSetList={...
                [PartName,' End Front Face']...
                [PartName,' End Back Face']...
                };
            elseif contains(PartName,'Magnet') 
                FaceGeomSetList={...
                [PartName,'-Core Face']
                };
            else
                FaceGeomSetList={...
                [PartName,'-Face']
                };
            end
end