# Ansys Electronics Desktop VBS file generated by Motor-CAD at 15/07/2025  2:55:10
# 2D Electromagnetic model
# Program Version: 2025.1.1.1
# Licence_Name: 1055@ansys-license-server;

import os
from datetime import datetime

# Code below is autogenerated - do not change
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")

# Disable auto-save while running vbs script in Maxwell to speed up process.
autoSaveConfig = oDesktop.GetAutoSaveEnabled()
oDesktop.EnableAutoSave(0)

# Check version so correct project file extension is used
versionArray = oDesktop.GetVersion().split(".")
if versionArray[0] < 2016:
  projExt = ".mxwl"
else:
  projExt = ".aedt"  # R17 or later


oDesktop.RestoreWindow()
oProject = oDesktop.NewProject()
oProject.InsertDesign("Maxwell 2D", "Motor-CAD cbh", "Transient", "")
oDefinitionManager = oProject.GetDefinitionManager()
oMaterialMgr = oDefinitionManager.GetManager("Material")
oDesign = oProject.SetActiveDesign("Motor-CAD cbh")

ModelName = "cbh"
ModelName_ANSYSEM = "cbh_ANSYSEM_2D"
designName = "Motor-CAD" + ModelName
# Add timestamp to model name if project with same name already exists
projects = oDesktop.GetProjects()
for project in projects:
  project_name = project.GetName()
  if project_name == ModelName_ANSYSEM:
     # Replace slashes and colons in timestamp so only valid characters used for project name
    currentTime = datetime.now().replace(":", ".")
    currentTime = currentTime.replace("/", "-")
    currentTime = currentTime.replace(" ", "_")
    ModelName_ANSYSEM = ModelName_ANSYSEM + "_" + currentTime
    break

oProject.SaveAs("d:\\KangDH\\Emlab_emach\\tools\\ansys\\" + ModelName_ANSYSEM + projExt, True)

# Start of writing parameters
oDesign.ChangeProperty(["NAME:AllTabs", ["NAME:LocalVariableTab",
  ["NAME:PropServers", "LocalVariables"], ["NAME:NewProps",
  ["NAME:Is_2D_Design", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1"],
  ["NAME:DiaGap", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","80mm"],
  ["NAME:DiaStatorYoke", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","130mm"],
  ["NAME:DiaShaft", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","25mm"],
  ["NAME:DiaShaft_Effective", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","25mm"],
  ["NAME:DiaOuter", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","130mm"],
  ["NAME:Airgap", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1mm"],
  ["NAME:StatorSkewAngle", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0deg"],
  ["NAME:Model_Length", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:Magnet_Length", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","90mm"],
  ["NAME:Stator_Lam_Length", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:Rotor_Lam_Length", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:RotorDia", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","78mm"],
  ["NAME:Rotor_Slices", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1"],
  ["NAME:SlotNumber_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","18"],
  ["NAME:SlotType_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","3"],
  ["NAME:Hs0_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1mm"],
  ["NAME:Hs1_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1.39513973428065mm"],
  ["NAME:Hs2_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","15.2555195114007mm"],
  ["NAME:Bs0_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","3mm"],
  ["NAME:Bs1_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","7.83290580686447mm"],
  ["NAME:Bs2_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","13.2128251960332mm"],
  ["NAME:Rs_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:FilletType_Stator", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","3"],
  ["NAME:Magnetic_Axial_Length", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","90mm"],
  ["NAME:Layers", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","2"],
  ["NAME:ParallelPaths", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1"],
  ["NAME:SpanExt", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","34.9670692955881mm"],
  ["NAME:WdgExt_Avg", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","5mm"],
  ["NAME:HalfAxial", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0"],
  ["NAME:SymmetryFactor", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","2"],
  ["NAME:SegAngle", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0deg"],
  ["NAME:SegAngle_Coil_Armature", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","10deg"],
  ["NAME:NumPoles", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","4"],
  ["NAME:Magnet_Axial_Offset", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:Axial_Segments", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1"],
  ["NAME:PoleType_PMCore", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","2"],
  ["NAME:Embrace_Rotor", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0.777777777777778"],
  ["NAME:Embrace_Magnet", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0.777777777777778"],
  ["NAME:ThickMag", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","4mm"],
  ["NAME:Offset_PMCore", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0"],
  ["NAME:Shaft_Hole_Diameter", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:Sleeve_Thickness", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"],
  ["NAME:Banding_Thickness", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0mm"]]]]
)
# End of writing parameters

# Drive Variables
oDesign.ChangeProperty(["NAME:AllTabs", ["NAME:LocalVariableTab",
  ["NAME:PropServers", "LocalVariables"], ["NAME:NewProps",
  ["NAME:IPeak", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","5A"],
  ["NAME:PhaseAdvance", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0deg"],
  ["NAME:MachineRPM", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","3000RPM"],
  ["NAME:Vpeak", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0V"],
  ["NAME:Rphase", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0ohm"],
  ["NAME:PhasorAngle", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0deg"],
  ["NAME:MaxPhasorAngle", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","120deg"],
  ["NAME:PeakDriveVoltage", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","Vpeak / (2*sin(MaxPhasorAngle / 2))"],
  ["NAME:Lend", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","0H"],
  ["NAME:NumTorqueCycles", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","1"],
  ["NAME:NumTorquePointsPerCycle", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","30"],
  ["NAME:DriveOffsetED", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","30deg"],
  ["NAME:InitialPositionMD", "PropType:=", "VariableProp","UserDef:=", True, "Value:=","DriveOffsetED / (NumPoles/2)"]]]]
)
# End of Drive Variables


# Create local variables
oEditor = oDesign.SetActiveEditor("3D Modeler")
oBoundaryModule = oDesign.GetModule("BoundarySetup")
oModelModule = oDesign.GetModule("ModelSetup")
oMeshModule = oDesign.GetModule("MeshSetup")
oAnalysisModule = oDesign.GetModule("AnalysisSetup")
oReportModule = oDesign.GetModule("ReportSetup")
oOutputVarModule = oDesign.GetModule("OutputVariable")


# Materials
oDefinitionManager.ModifyLibraries(designName, ["NAME:PersonalLib"],
  ["NAME:UserLib"], ["NAME:SystemLib", "Materials:=", ["Materials", "Motor-CAD"]])

# Material with BH curve
if oDefinitionManager.DoesMaterialExist("M350-50A_20C"):
  pass
else:
  oDefinitionManager.AddMaterial(["NAME:M350-50A_20C",
    "CoordinateSystemType:=", "Cartesian",
    ["NAME:AttachedData",
     ["NAME:MatNotesData",
      "property_data:=", "notes_data",
      "Notes:=", ", "]],
    ["NAME:ModifierData"],
    ["NAME:permeability",
     "property_type:=", "nonlinear",
     "HUnit:=", "A_per_meter",
     "BUnit:=", "tesla",
     ["NAME:BHCoordinates",
      ["NAME:Coordinate", "X:=", 0, "Y:=", 0],
      ["NAME:Coordinate", "X:=", 34.8, "Y:=", 0.1],
      ["NAME:Coordinate", "X:=", 46, "Y:=", 0.2],
      ["NAME:Coordinate", "X:=", 53.7, "Y:=", 0.3],
      ["NAME:Coordinate", "X:=", 60.6, "Y:=", 0.4],
      ["NAME:Coordinate", "X:=", 67.4, "Y:=", 0.5],
      ["NAME:Coordinate", "X:=", 74.6, "Y:=", 0.6],
      ["NAME:Coordinate", "X:=", 82.6, "Y:=", 0.7],
      ["NAME:Coordinate", "X:=", 91.8, "Y:=", 0.8],
      ["NAME:Coordinate", "X:=", 103, "Y:=", 0.9],
      ["NAME:Coordinate", "X:=", 119, "Y:=", 1],
      ["NAME:Coordinate", "X:=", 141, "Y:=", 1.1],
      ["NAME:Coordinate", "X:=", 178, "Y:=", 1.2],
      ["NAME:Coordinate", "X:=", 250, "Y:=", 1.3],
      ["NAME:Coordinate", "X:=", 455, "Y:=", 1.4],
      ["NAME:Coordinate", "X:=", 1180, "Y:=", 1.5],
      ["NAME:Coordinate", "X:=", 3020, "Y:=", 1.6],
      ["NAME:Coordinate", "X:=", 6100, "Y:=", 1.7],
      ["NAME:Coordinate", "X:=", 10700, "Y:=", 1.8],
      ["NAME:Coordinate", "X:=", 25000, "Y:=", 1.9],
      ["NAME:Coordinate", "X:=", 35000, "Y:=", 1.956],
      ["NAME:Coordinate", "X:=", 75000, "Y:=", 2.1],
      ["NAME:Coordinate", "X:=", 115000, "Y:=", 2.2],
      ["NAME:Coordinate", "X:=", 150000, "Y:=", 2.2701],
      ["NAME:Coordinate", "X:=", 229580, "Y:=", 2.4]]],
    ["NAME:core_loss_type",
     "property_type:=", "ChoiceProperty",
     "Choice:=", "Electrical Steel"],
    "core_loss_kh:=", 159.9615,
    "core_loss_kc:=", 0.934621628891037,
    "core_loss_ke:=", 0,
    "core_loss_es_y:=", 2,
    "core_loss_kdc:=", "0",
    "conductivity:=", 2272727.27272727,
    "mass_density:=", 7650,
    ["NAME:stacking_type", "property_type:=",
     "ChoiceProperty", "Choice:=", "Lamination"],
     "stacking_factor:=", "0.97",
    ["NAME:stacking_direction",
     "property_type:=", "ChoiceProperty",
     "Choice:=", "V(3)"]]
  )

# Simple Material
if oDefinitionManager.DoesMaterialExist("Copper (Pure)_40C"):
  pass
else:
  oDefinitionManager.AddMaterial(["NAME:Copper (Pure)_40C",
    "CoordinateSystemType:=", "Cartesian",
    ["NAME:AttachedData",
     ["NAME:MatNotesData",
      "property_data:=", "notes_data",
      "Notes:=", ""]],
    ["NAME:ModifierData"],
    "conductivity:=", "53845605.7807264",
    "mass_density:=", "8933"]
  )

# Magnet Material
if oDefinitionManager.DoesMaterialExist("N30UH_20C"):
  pass
else:
  oDefinitionManager.AddMaterial(["NAME:N30UH_20C",
    "CoordinateSystemType:=","Cartesian",
    ["NAME:AttachedData",
     ["NAME:MatNotesData",
      "property_data:=", "notes_data",
      "Notes:=", " (Applied loss factor on conductivity = 0.598911364658355)"]],
      ["NAME:permeability",
       "property_type:=", "nonlinear",
       "BTypeForSingleCurve:=", "intrinsic",
       "HUnit:=", "A_per_meter",
       "BUnit:=", "tesla",
       "IsTemperatureDependent:=", "False",
       ["NAME:BHCoordinates",
        ["NAME:Coordinate", "X:=", -1990000, "Y:=", 0],
        ["NAME:Coordinate", "X:=", -1989534.1130981, "Y:=", 0.0275944351206854],
        ["NAME:Coordinate", "X:=", -1989057.31913061, "Y:=", 0.0550483074802632],
        ["NAME:Coordinate", "X:=", -1988569.36274782, "Y:=", 0.0823443009621321],
        ["NAME:Coordinate", "X:=", -1988069.98262194, "Y:=", 0.109464989534283],
        ["NAME:Coordinate", "X:=", -1987558.91130714, "Y:=", 0.136392871260207],
        ["NAME:Coordinate", "X:=", -1987035.87509627, "Y:=", 0.163110403983081],
        ["NAME:Coordinate", "X:=", -1986500.59387436, "Y:=", 0.189600042625376],
        ["NAME:Coordinate", "X:=", -1985952.78096853, "Y:=", 0.215844278033058],
        ["NAME:Coordinate", "X:=", -1985392.14299447, "Y:=", 0.241825677281118],
        ["NAME:Coordinate", "X:=", -1984818.37969937, "Y:=", 0.26752692534294],
        ["NAME:Coordinate", "X:=", -1984231.18380106, "Y:=", 0.292930868013032],
        ["NAME:Coordinate", "X:=", -1983630.24082345, "Y:=", 0.318020555957734],
        ["NAME:Coordinate", "X:=", -1983015.22892816, "Y:=", 0.342779289754597],
        ["NAME:Coordinate", "X:=", -1982385.81874208, "Y:=", 0.367190665766652],
        ["NAME:Coordinate", "X:=", -1981741.67318105, "Y:=", 0.391238622683161],
        ["NAME:Coordinate", "X:=", -1981082.44726928, "Y:=", 0.414907488544342],
        ["NAME:Coordinate", "X:=", -1980407.7879546, "Y:=", 0.438182028053552],
        ["NAME:Coordinate", "X:=", -1979717.33391943, "Y:=", 0.461047489966685],
        ["NAME:Coordinate", "X:=", -1979010.7153872, "Y:=", 0.483489654335753],
        ["NAME:Coordinate", "X:=", -1978287.55392438, "Y:=", 0.505494879371257],
        ["NAME:Coordinate", "X:=", -1977547.46223777, "Y:=", 0.52705014767674],
        ["NAME:Coordinate", "X:=", -1976790.04396708, "Y:=", 0.548143111598682],
        ["NAME:Coordinate", "X:=", -1976014.8934727, "Y:=", 0.568762137426032],
        ["NAME:Coordinate", "X:=", -1975221.59561841, "Y:=", 0.588896348166387],
        ["NAME:Coordinate", "X:=", -1974409.72554906, "Y:=", 0.608535664619907],
        ["NAME:Coordinate", "X:=", -1973578.84846305, "Y:=", 0.627670844468485],
        ["NAME:Coordinate", "X:=", -1972728.51937949, "Y:=", 0.646293519095763],
        ["NAME:Coordinate", "X:=", -1971858.28289982, "Y:=", 0.664396227854041],
        ["NAME:Coordinate", "X:=", -1970967.67296401, "Y:=", 0.681972449497292],
        ["NAME:Coordinate", "X:=", -1970056.21260087, "Y:=", 0.699016630504428],
        ["NAME:Coordinate", "X:=", -1969123.41367266, "Y:=", 0.715524210025726],
        ["NAME:Coordinate", "X:=", -1968168.77661367, "Y:=", 0.731491641195802],
        ["NAME:Coordinate", "X:=", -1967191.79016262, "Y:=", 0.746916408570688],
        ["NAME:Coordinate", "X:=", -1966191.93108891, "Y:=", 0.761797041463351],
        ["NAME:Coordinate", "X:=", -1965168.66391238, "Y:=", 0.776133122971899],
        ["NAME:Coordinate", "X:=", -1964121.44061652, "Y:=", 0.789925294517497],
        ["NAME:Coordinate", "X:=", -1963049.70035498, "Y:=", 0.803175255735102],
        ["NAME:Coordinate", "X:=", -1961952.86915123, "Y:=", 0.815885759588605],
        ["NAME:Coordinate", "X:=", -1960830.35959113, "Y:=", 0.828060602613589],
        ["NAME:Coordinate", "X:=", -1959681.57050835, "Y:=", 0.839704610225],
        ["NAME:Coordinate", "X:=", -1958505.88666241, "Y:=", 0.850823617063303],
        ["NAME:Coordinate", "X:=", -1957302.67840922, "Y:=", 0.86142444239131],
        ["NAME:Coordinate", "X:=", -1956071.30136378, "Y:=", 0.871514860594035],
        ["NAME:Coordinate", "X:=", -1954811.0960552, "Y:=", 0.881103566875525],
        ["NAME:Coordinate", "X:=", -1953521.3875734, "Y:=", 0.890200138289217],
        ["NAME:Coordinate", "X:=", -1952201.48520773, "Y:=", 0.898814990281414],
        ["NAME:Coordinate", "X:=", -1950850.68207704, "Y:=", 0.906959328970498],
        ["NAME:Coordinate", "X:=", -1949468.25475109, "Y:=", 0.914645099427005],
        ["NAME:Coordinate", "X:=", -1948053.46286314, "Y:=", 0.921884930261099],
        ["NAME:Coordinate", "X:=", -1946605.5487134, "Y:=", 0.928692074863553],
        ["NAME:Coordinate", "X:=", -1945123.73686328, "Y:=", 0.935080349683876],
        ["NAME:Coordinate", "X:=", -1943607.2337201, "Y:=", 0.941064069963507],
        ["NAME:Coordinate", "X:=", -1942055.22711204, "Y:=", 0.946657983373127],
        ["NAME:Coordinate", "X:=", -1940466.88585321, "Y:=", 0.951877202029943],
        ["NAME:Coordinate", "X:=", -1938841.35929848, "Y:=", 0.956737133393114],
        ["NAME:Coordinate", "X:=", -1937177.77688795, "Y:=", 0.961253410552676],
        ["NAME:Coordinate", "X:=", -1935475.24768067, "Y:=", 0.965441822438914],
        ["NAME:Coordinate", "X:=", -1933732.85987753, "Y:=", 0.969318244484887],
        ["NAME:Coordinate", "X:=", -1931949.6803329, "Y:=", 0.972898570274232],
        ["NAME:Coordinate", "X:=", -1930124.75405492, "Y:=", 0.976198644699484],
        ["NAME:Coordinate", "X:=", -1928257.10369404, "Y:=", 0.97923419914264],
        ["NAME:Coordinate", "X:=", -1926345.72901957, "Y:=", 0.982020789169791],
        ["NAME:Coordinate", "X:=", -1924389.60638402, "Y:=", 0.98457373520517],
        ["NAME:Coordinate", "X:=", -1922387.68817488, "Y:=", 0.986908066617511],
        ["NAME:Coordinate", "X:=", -1920338.90225356, "Y:=", 0.989038469613212],
        ["NAME:Coordinate", "X:=", -1918242.15138121, "Y:=", 0.990979239287136],
        ["NAME:Coordinate", "X:=", -1916096.31263108, "Y:=", 0.992744236133454],
        ["NAME:Coordinate", "X:=", -1913900.23678711, "Y:=", 0.994346847266427],
        ["NAME:Coordinate", "X:=", -1911652.7477285, "Y:=", 0.995799952545286],
        ["NAME:Coordinate", "X:=", -1909352.64179982, "Y:=", 0.997115895739185],
        ["NAME:Coordinate", "X:=", -1906998.68716635, "Y:=", 0.998306460808575],
        ["NAME:Coordinate", "X:=", -1904589.62315443, "Y:=", 0.999382853319193],
        ["NAME:Coordinate", "X:=", -1902124.15957622, "Y:=", 1.00035568694529],
        ["NAME:Coordinate", "X:=", -1899600.9760388, "Y:=", 1.00123497496054],
        ["NAME:Coordinate", "X:=", -1897018.72123701, "Y:=", 1.00203012655964],
        ["NAME:Coordinate", "X:=", -1894376.01222971, "Y:=", 1.00274994780129],
        ["NAME:Coordinate", "X:=", -1891671.4336992, "Y:=", 1.00340264691566],
        ["NAME:Coordinate", "X:=", -1888903.53719318, "Y:=", 1.00399584367674],
        ["NAME:Coordinate", "X:=", -1886070.84034907, "Y:=", 1.00453658250313],
        ["NAME:Coordinate", "X:=", -1883171.8261001, "Y:=", 1.00503134892048],
        ["NAME:Coordinate", "X:=", -1880204.94186284, "Y:=", 1.00548608899513],
        ["NAME:Coordinate", "X:=", -1877168.5987057, "Y:=", 1.00590623133195],
        ["NAME:Coordinate", "X:=", -1874061.17049798, "Y:=", 1.00629671122005],
        ["NAME:Coordinate", "X:=", -1870880.99303897, "Y:=", 1.00666199650773],
        ["NAME:Coordinate", "X:=", -1867626.36316671, "Y:=", 1.00700611479267],
        ["NAME:Coordinate", "X:=", -1864295.5378458, "Y:=", 1.00733268152475],
        ["NAME:Coordinate", "X:=", -1860886.73323396, "Y:=", 1.00764492863568],
        ["NAME:Coordinate", "X:=", -1857398.12372665, "Y:=", 1.00794573333284],
        ["NAME:Coordinate", "X:=", -1853827.84097938, "Y:=", 1.00823764672151],
        ["NAME:Coordinate", "X:=", -1850173.97290708, "Y:=", 1.00852292195108],
        ["NAME:Coordinate", "X:=", -1846434.5626601, "Y:=", 1.00880354161492],
        ["NAME:Coordinate", "X:=", -1842607.6075762, "Y:=", 1.00908124416973],
        ["NAME:Coordinate", "X:=", -1838691.05810798, "Y:=", 1.00935754917761],
        ["NAME:Coordinate", "X:=", -1834682.8167253, "Y:=", 1.00963378121178],
        ["NAME:Coordinate", "X:=", -1830580.73679187, "Y:=", 1.00991109230384],
        ["NAME:Coordinate", "X:=", -1826382.62141565, "Y:=", 1.01019048284633],
        ["NAME:Coordinate", "X:=", -1822086.22227227, "Y:=", 1.01047282089822],
        ["NAME:Coordinate", "X:=", -1817689.23840094, "Y:=", 1.01075885987196],
        ["NAME:Coordinate", "X:=", -1813189.31497215, "Y:=", 1.01104925460894],
        ["NAME:Coordinate", "X:=", -1808584.04202652, "Y:=", 1.01134457587526],
        ["NAME:Coordinate", "X:=", -1803870.95318416, "Y:=", 1.0116453233303],
        ["NAME:Coordinate", "X:=", -1799047.52432375, "Y:=", 1.01195193703883],
        ["NAME:Coordinate", "X:=", -1794111.17223077, "Y:=", 1.01226480761049],
        ["NAME:Coordinate", "X:=", -1789059.253214, "Y:=", 1.01258428506115],
        ["NAME:Coordinate", "X:=", -1783889.06168972, "Y:=", 1.01291068649733],
        ["NAME:Coordinate", "X:=", -1778597.82873271, "Y:=", 1.01324430272862],
        ["NAME:Coordinate", "X:=", -1773182.72059331, "Y:=", 1.01358540391414],
        ["NAME:Coordinate", "X:=", -1767640.83717981, "Y:=", 1.01393424434746],
        ["NAME:Coordinate", "X:=", -1761969.21050529, "Y:=", 1.01429106648118],
        ["NAME:Coordinate", "X:=", -1756164.80309811, "Y:=", 1.01465610428733],
        ["NAME:Coordinate", "X:=", -1750224.50637513, "Y:=", 1.01502958604335],
        ["NAME:Coordinate", "X:=", -1744145.13897695, "Y:=", 1.01541173662646],
        ["NAME:Coordinate", "X:=", -1737923.44506406, "Y:=", 1.0158027793916],
        ["NAME:Coordinate", "X:=", -1731556.0925732, "Y:=", 1.01620293770013],
        ["NAME:Coordinate", "X:=", -1725039.67143283, "Y:=", 1.01661243615893],
        ["NAME:Coordinate", "X:=", -1718370.69173685, "Y:=", 1.01703150162168],
        ["NAME:Coordinate", "X:=", -1711545.58187558, "Y:=", 1.01746036399709],
        ["NAME:Coordinate", "X:=", -1704560.68662293, "Y:=", 1.01789925690223],
        ["NAME:Coordinate", "X:=", -1697412.26517885, "Y:=", 1.0183484181929],
        ["NAME:Coordinate", "X:=", -1690096.48916593, "Y:=", 1.0188080903977],
        ["NAME:Coordinate", "X:=", -1682609.44057906, "Y:=", 1.01927852107762],
        ["NAME:Coordinate", "X:=", -1674947.10968714, "Y:=", 1.0197599631289],
        ["NAME:Coordinate", "X:=", -1667105.39288564, "Y:=", 1.02025267504331],
        ["NAME:Coordinate", "X:=", -1659080.09049891, "Y:=", 1.0207569211372],
        ["NAME:Coordinate", "X:=", -1650866.90453098, "Y:=", 1.02127297175807],
        ["NAME:Coordinate", "X:=", -1642461.43636379, "Y:=", 1.0218011034754],
        ["NAME:Coordinate", "X:=", -1633859.18440145, "Y:=", 1.02234159926114],
        ["NAME:Coordinate", "X:=", -1625055.54165941, "Y:=", 1.02289474866365],
        ["NAME:Coordinate", "X:=", -1616045.79329714, "Y:=", 1.02346084797812],
        ["NAME:Coordinate", "X:=", -1606825.1140931, "Y:=", 1.02404020041564],
        ["NAME:Coordinate", "X:=", -1597388.56586052, "Y:=", 1.02463311627248],
        ["NAME:Coordinate", "X:=", -1587731.09480278, "Y:=", 1.02523991310088],
        ["NAME:Coordinate", "X:=", -1577847.52880679, "Y:=", 1.02586091588211],
        ["NAME:Coordinate", "X:=", -1567732.57467303, "Y:=", 1.02649645720235],
        ["NAME:Coordinate", "X:=", -1557380.81528077, "Y:=", 1.02714687743211],
        ["NAME:Coordinate", "X:=", -1546786.70668688, "Y:=", 1.02781252490922],
        ["NAME:Coordinate", "X:=", -1535944.57515674, "Y:=", 1.02849375612586],
        ["NAME:Coordinate", "X:=", -1524848.61412568, "Y:=", 1.02919093591977],
        ["NAME:Coordinate", "X:=", -1513492.88108917, "Y:=", 1.02990443766981],
        ["NAME:Coordinate", "X:=", -1501871.29442034, "Y:=", 1.03063464349604],
        ["NAME:Coordinate", "X:=", -1489977.6301129, "Y:=", 1.03138194446439],
        ["NAME:Coordinate", "X:=", -1477805.51844785, "Y:=", 1.03214674079615],
        ["NAME:Coordinate", "X:=", -1465348.44058214, "Y:=", 1.03292944208234],
        ["NAME:Coordinate", "X:=", -1452599.72505746, "Y:=", 1.03373046750305],
        ["NAME:Coordinate", "X:=", -1439552.5442273, "Y:=", 1.03455024605198],
        ["NAME:Coordinate", "X:=", -1426199.91060038, "Y:=", 1.03538921676615],
        ["NAME:Coordinate", "X:=", -1412534.67309846, "Y:=", 1.03624782896106],
        ["NAME:Coordinate", "X:=", -1398549.51322651, "Y:=", 1.03712654247132],
        ["NAME:Coordinate", "X:=", -1384236.94115329, "Y:=", 1.0380258278969],
        ["NAME:Coordinate", "X:=", -1369589.2917001, "Y:=", 1.03894616685519],
        ["NAME:Coordinate", "X:=", -1354598.72023567, "Y:=", 1.03988805223891],
        ["NAME:Coordinate", "X:=", -1339257.19847489, "Y:=", 1.04085198848008],
        ["NAME:Coordinate", "X:=", -1323556.51017925, "Y:=", 1.0418384918202],
        ["NAME:Coordinate", "X:=", -1307488.2467566, "Y:=", 1.04284809058669],
        ["NAME:Coordinate", "X:=", -1291043.80275782, "Y:=", 1.04388132547587],
        ["NAME:Coordinate", "X:=", -1274214.37126819, "Y:=", 1.04493874984251],
        ["NAME:Coordinate", "X:=", -1256990.93919075, "Y:=", 1.04602092999619],
        ["NAME:Coordinate", "X:=", -1239364.2824193, "Y:=", 1.0471284455046],
        ["NAME:Coordinate", "X:=", -1221324.96089841, "Y:=", 1.04826188950391],
        ["NAME:Coordinate", "X:=", -1202863.31356767, "Y:=", 1.04942186901646],
        ["NAME:Coordinate", "X:=", -1183969.45318776, "Y:=", 1.05060900527581],
        ["NAME:Coordinate", "X:=", -1164633.26104516, "Y:=", 1.05182393405948],
        ["NAME:Coordinate", "X:=", -1144844.38153312, "Y:=", 1.05306730602944],
        ["NAME:Coordinate", "X:=", -1124592.21660561, "Y:=", 1.05433978708055],
        ["NAME:Coordinate", "X:=", -1103865.92010148, "Y:=", 1.05564205869722],
        ["NAME:Coordinate", "X:=", -1082654.39193573, "Y:=", 1.05697481831836],
        ["NAME:Coordinate", "X:=", -1060946.27215482, "Y:=", 1.0583387797109],
        ["NAME:Coordinate", "X:=", -1038729.93485277, "Y:=", 1.05973467335205],
        ["NAME:Coordinate", "X:=", -1015993.48194483, "Y:=", 1.06116324682054],
        ["NAME:Coordinate", "X:=", -992724.736795407, "Y:=", 1.06262526519693],
        ["NAME:Coordinate", "X:=", -968911.237696804, "Y:=", 1.06412151147342],
        ["NAME:Coordinate", "X:=", -944540.231195266, "Y:=", 1.06565278697314],
        ["NAME:Coordinate", "X:=", -919598.665260806, "Y:=", 1.06721991177931],
        ["NAME:Coordinate", "X:=", -894073.182297114, "Y:=", 1.06882372517447],
        ["NAME:Coordinate", "X:=", -867950.111987823, "Y:=", 1.07046508608993],
        ["NAME:Coordinate", "X:=", -841215.463975293, "Y:=", 1.07214487356578],
        ["NAME:Coordinate", "X:=", -813854.920367994, "Y:=", 1.07386398722168],
        ["NAME:Coordinate", "X:=", -785853.82807248, "Y:=", 1.07562334773864],
        ["NAME:Coordinate", "X:=", -757197.190945844, "Y:=", 1.07742389735211],
        ["NAME:Coordinate", "X:=", -727869.661764447, "Y:=", 1.0792666003566],
        ["NAME:Coordinate", "X:=", -697855.534004624, "Y:=", 1.08115244362208],
        ["NAME:Coordinate", "X:=", -667138.733430972, "Y:=", 1.08308243712256],
        ["NAME:Coordinate", "X:=", -635702.809487697, "Y:=", 1.08505761447694],
        ["NAME:Coordinate", "X:=", -603530.926488429, "Y:=", 1.08707903350259],
        ["NAME:Coordinate", "X:=", -570605.854599776, "Y:=", 1.08914777678188],
        ["NAME:Coordinate", "X:=", -536909.960613787, "Y:=", 1.09126495224193],
        ["NAME:Coordinate", "X:=", -502425.19850439, "Y:=", 1.093431693748],
        ["NAME:Coordinate", "X:=", -467133.099762737, "Y:=", 1.09564916171074],
        ["NAME:Coordinate", "X:=", -431014.763506299, "Y:=", 1.0979185437076],
        ["NAME:Coordinate", "X:=", -394050.846356382, "Y:=", 1.10024105511892],
        ["NAME:Coordinate", "X:=", -356221.552078674, "Y:=", 1.10261793977879],
        ["NAME:Coordinate", "X:=", -317506.620981267, "Y:=", 1.10505047064118],
        ["NAME:Coordinate", "X:=", -277885.319064453, "Y:=", 1.10753995046173],
        ["NAME:Coordinate", "X:=", -237336.426916523, "Y:=", 1.1100877124954],
        ["NAME:Coordinate", "X:=", -195838.228349586, "Y:=", 1.1126951212105],
        ["NAME:Coordinate", "X:=", -153368.498769347, "Y:=", 1.11536357301948],
        ["NAME:Coordinate", "X:=", -109904.493272596, "Y:=", 1.11809449702677],
        ["NAME:Coordinate", "X:=", -65422.9344660472, "Y:=", 1.1208893557941],
        ["NAME:Coordinate", "X:=", -19900, "Y:=", 1.12374964612387],
        ["NAME:Coordinate", "X:=", 0, "Y:=", 1.125]]],
    "conductivity:=", "332728.535921308",
    "mass_density:=", "7500",
    ["NAME:magnetic_coercivity",
     "property_type:=", "VectorProperty",
    "Magnitude:=", "-1990000A_per_meter",
    "DirComp1:=", "1",
    "DirComp2:=", "0",
    "DirComp3:=", "0"]]
  )

# End Materials

# Ansys script methods
def ChangePropertyName(name, name_New):
  oEditor.ChangeProperty(["NAME:AllTabs",
    ["NAME:Geometry3DAttributeTab",
    ["NAME:PropServers", str(name)],
    ["NAME:ChangedProps",
    ["NAME:Name", "Value:=", str(name_New)]]]])

def SubtractObjects(blankPartList, toolPartList, keepOriginals):
  # Subtract tool parts boundaries from blank part boundaries
  oEditor.Subtract(["NAME:Selections",
    "Blank Parts:=", str(blankPartList),
    "Tool Parts:=", str(toolPartList)],
    ["NAME:SubtractParameters", "KeepOriginals:=", keepOriginals])

def CreateOutputVariable(variableName, Expression):
  oOutputVarModule.CreateOutputVariable(str(variableName),
    str(Expression),
    "Setup1 : Transient", "Transient", [])

def BandToolSubtraction(bandTool):
  numObjects = oEditor.GetNumObjects()
  objectString = ""
  for objectLoop in range(numObjects - 1):
    name = oEditor.GetObjectName(int(objectLoop))
    if bandTool != str(name):
      objectString = objectString + str(name) + ","

  oEditor.Subtract(["NAME:Selections",
    "Blank Parts:=", str(objectString),
    "Tool Parts:=", str(bandTool)],
    ["NAME:SubtractParameters", "KeepOriginals:=",  False])

def RotateObject(name, skewAngle):
  oEditor.Rotate(["NAME:Selections",
	  "Selections:=", str(name),
    "NewPartsModelFlag:=", "Model"],
	  ["NAME:RotateParameters",
     "RotateAxis:=", "Z",
     "RotateAngle:=", str(skewAngle).replace(",", ".") + "deg"])

def SplitObject(name, side):
  oEditor.Split(["NAME:Selections",
    "Selections:=", str(name),
    "NewPartsModelFlag:=", "Model"],
    ["Name:SplitToParameters",
     "SplitPlane:=", "ZX",
     "WhichSide:=", str(side),
     "ToolType:=", "PlaneTool",
     "ToolEntityID:=", -1,
     "SplitCrossingObjectsOnly:=", False,
     "DeleteInvalidObjects:=", True])

def CreateRectangleObject(name, Xstart, Ystart, Zstart, Width, Height, Axis):
  oEditor.CreateRectangle(["NAME:RectangleParameters",
    "IsCovered:=", True,
    "XStart:=", str(Xstart),
    "YStart:=", str(Ystart),
    "ZStart:=", str(Zstart),
    "Width:=", str(Width),
    "Height:=", str(Height),
    "WhichAxis:=", str(Axis)],
    ["NAME:Attributes",
     "Name:=", str(name),
     "Flags:=", "",
     "Color:=", "(143 175 143)",
     "Transparency:=", 0,
     "PartCoordinateSystem:=", "Global",
     "UDMId:=", "",
     "MaterialValue:=", "\"\"",
     "SurfaceMaterialValue:=", "\"\"",
     "SolveInside:=", True,
     "ShellElement:=", False,
     "ShellElementThicknesS:=", "0mm",
     "ReferenceTemperature:=", "20cel",
     "IsMaterialEditable:=", True,
     "UseMaterialAppearance:=", False,
     "IsLightweight:=", False])

def SeparateCoil(coilName, R, G, B):
  oEditor.SeparateBody(["NAME:Selections",
	  "Selections:=", str(coilName),
	  "NewPartsModelFlag:=", "Model"],
	  ["CreateGroupsForNewObjects:=", False])

  ChangePropertyName(str(coilName), str(coilName) + "_1")
  ChangePropertyName(str(coilName) + "_Separate1", str(coilName) + "_2")

  oEditor.ChangeProperty(["NAME:AllTabs", ["NAME:Geometry3DAttributeTab",
    ["NAME:PropServers", str(coilName) + "_2"],
    ["NAME:ChangedProps",
    ["NAME:Color", "R:=", int(R), "G:=",  int(G), "B:=",  int(B)]]]])

def CreateMagnetCoordinateSystem(magnetName, origin_X, origin_Y, origin_Z, vector_XX, vector_XY, vector_YX, vector_YY, ModelType):
  oEditor.SetWCS(["NAME:SetWCS Parameter", "Working Coordinate System:=", "Global"])
  oEditor.CreateRelativeCS(["NAME:RelativeCSParameters",
    "Mode:=", "Axis/Position",
    "OriginX:=", str(origin_X).replace(",", ".") + "mm",
    "OriginY:=", str(origin_Y).replace(",", ".") + "mm",
    "OriginZ:=", str(origin_Z).replace(",", ".") + "mm",
    "XAxisXvec:=", str(vector_XX).replace(",", ".") + "mm",
    "XAxisYvec:=", str(vector_XY).replace(",", ".") + "mm",
    "XAxisZvec:=", "0mm",
    "YAxisXvec:=", str(vector_YX).replace(",", ".") + "mm",
    "YAxisYvec:=", str(vector_YY).replace(",", ".") + "mm",
    "YAxisZvec:=", "0mm"],
    ["NAME:Attributes", "Name:=", "CS_" + str(magnetName)])

  oEditor.ChangeProperty(["NAME:AllTabs",
    ["NAME:Geometry3DAttributeTab",
     ["NAME:PropServers", str(magnetName)],
     ["NAME:ChangedProps",
      ["NAME:Orientation", "Value:=", "CS_" + str(magnetName)]]]])

  if ModelType == 0:
    # Assign excitation to magnets for magnet eddy current loss calculations
    oBoundaryModule.AssignCurrent(["NAME:" + str(magnetName),
      "Objects:=", [str(magnetName)],
      "Current:=", "0A" ,
      "IsPositive:=", True])

# Components
# Create Stator Primitive
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/VentSlotCore.dll", "Version:=", "16.0", "NoOfParameters:=", 19, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "DiaGap"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs01", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
  ["NAME:Pair", "Name:=", "VentHoles", "Value:=", "0"],
  ["NAME:Pair", "Name:=", "HoleDiaIn", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "HoleDiaOut", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "HoleLocIn", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "HoleLocOut", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "VentDucts", "Value:=", "0"],
  ["NAME:Pair", "Name:=", "DuctWidth", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "DuctPitch", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle"],
  ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "0"]]],
  ["NAME:Attributes",
   "Name:=", "Stator_Lamination_Primitive",
   "Flags:=", "",
   "Color:=", "(240 0 16)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"M350-50A_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
# End of Stator primitive

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/PMCore.dll", "Version:=", "12.0", "NoOfParameters:=", 13, "Library:=",
  "syslib", ["NAME:ParamVector",
   ["NAME:Pair", "Name:=", "DiaGap",    "Value:=", "RotorDia"],
   ["NAME:Pair", "Name:=", "DiaYoke",   "Value:=", "DiaShaft_Effective"],
   ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Poles",     "Value:=", "NumPoles"],
   ["NAME:Pair", "Name:=", "PoleType",  "Value:=", "PoleType_PMCore"],
   ["NAME:Pair", "Name:=", "Embrace",   "Value:=", "Embrace_Rotor"],
   ["NAME:Pair", "Name:=", "ThickMag",  "Value:=", "ThickMag"],
   ["NAME:Pair", "Name:=", "WidthMag",  "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "OffSet",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Bridge",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Rib",       "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCore",  "Value:=", "0"]]],
  ["NAME:Attributes",
   "Name:=", "Rotor_Lamination_Primitive",
   "Flags:=", "",
   "Color:=", "(0 240 240)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"M350-50A_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
# End of Rotor Primitive

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/PMCore.dll", "Version:=", "12.0", "NoOfParameters:=", 13, "Library:=",
  "syslib", ["NAME:ParamVector",
   ["NAME:Pair", "Name:=", "DiaGap",    "Value:=", "RotorDia"],
   ["NAME:Pair", "Name:=", "DiaYoke",   "Value:=", "DiaShaft_Effective"],
   ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Poles",     "Value:=", "NumPoles"],
   ["NAME:Pair", "Name:=", "PoleType",  "Value:=", "PoleType_PMCore"],
   ["NAME:Pair", "Name:=", "Embrace",   "Value:=", "Embrace_Magnet"],
   ["NAME:Pair", "Name:=", "ThickMag",  "Value:=", "ThickMag"],
   ["NAME:Pair", "Name:=", "WidthMag",  "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "OffSet",    "Value:=", "Offset_PMCore"],
   ["NAME:Pair", "Name:=", "Bridge",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Rib",       "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCore",  "Value:=", "2"]]],
  ["NAME:Attributes",
   "Name:=", "1Magnet1N1_1_1",
   "Flags:=", "",
   "Color:=", "(0 212 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"N30UH_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

oEditor.CreateCircle(["NAME:CircleParameters",
  "IsCovered:=", True,
  "XCenter:=", "0mm",
  "YCenter:=", "0mm",
  "ZCenter:=", "0mm",
  "Radius:=", "DiaShaft / 2",
  "WhichAxis:=", "Z",
  "NumSegments:=", "0"],
  ["NAME:Attributes",
   "Name:=", "Shaft",
   "Flags:=", "",
   "Color:=", "(160 160 160)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"vacuum\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/PMCore.dll", "Version:=", "12.0", "NoOfParameters:=", 13, "Library:=",
  "syslib", ["NAME:ParamVector",
   ["NAME:Pair", "Name:=", "DiaGap",    "Value:=", "RotorDia"],
   ["NAME:Pair", "Name:=", "DiaYoke",   "Value:=", "DiaShaft_Effective"],
   ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Poles",     "Value:=", "NumPoles"],
   ["NAME:Pair", "Name:=", "PoleType",  "Value:=", "PoleType_PMCore"],
   ["NAME:Pair", "Name:=", "Embrace",   "Value:=", "Embrace_Magnet"],
   ["NAME:Pair", "Name:=", "ThickMag",  "Value:=", "ThickMag"],
   ["NAME:Pair", "Name:=", "WidthMag",  "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "OffSet",    "Value:=", "Offset_PMCore"],
   ["NAME:Pair", "Name:=", "Bridge",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Rib",       "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCore",  "Value:=", "2"]]],
  ["NAME:Attributes",
   "Name:=", "1Magnet1S2_1_1",
   "Flags:=", "",
   "Color:=", "(0 212 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"N30UH_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
RotateObject("1Magnet1S2_1_1",90)
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/PMCore.dll", "Version:=", "12.0", "NoOfParameters:=", 13, "Library:=",
  "syslib", ["NAME:ParamVector",
   ["NAME:Pair", "Name:=", "DiaGap",    "Value:=", "RotorDia"],
   ["NAME:Pair", "Name:=", "DiaYoke",   "Value:=", "DiaShaft_Effective"],
   ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Poles",     "Value:=", "NumPoles"],
   ["NAME:Pair", "Name:=", "PoleType",  "Value:=", "PoleType_PMCore"],
   ["NAME:Pair", "Name:=", "Embrace",   "Value:=", "Embrace_Magnet"],
   ["NAME:Pair", "Name:=", "ThickMag",  "Value:=", "ThickMag"],
   ["NAME:Pair", "Name:=", "WidthMag",  "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "OffSet",    "Value:=", "Offset_PMCore"],
   ["NAME:Pair", "Name:=", "Bridge",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Rib",       "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCore",  "Value:=", "2"]]],
  ["NAME:Attributes",
   "Name:=", "1Magnet1N2_1_1",
   "Flags:=", "",
   "Color:=", "(0 212 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"N30UH_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
RotateObject("1Magnet1N2_1_1",180)
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/PMCore.dll", "Version:=", "12.0", "NoOfParameters:=", 13, "Library:=",
  "syslib", ["NAME:ParamVector",
   ["NAME:Pair", "Name:=", "DiaGap",    "Value:=", "RotorDia"],
   ["NAME:Pair", "Name:=", "DiaYoke",   "Value:=", "DiaShaft_Effective"],
   ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Poles",     "Value:=", "NumPoles"],
   ["NAME:Pair", "Name:=", "PoleType",  "Value:=", "PoleType_PMCore"],
   ["NAME:Pair", "Name:=", "Embrace",   "Value:=", "Embrace_Magnet"],
   ["NAME:Pair", "Name:=", "ThickMag",  "Value:=", "ThickMag"],
   ["NAME:Pair", "Name:=", "WidthMag",  "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "OffSet",    "Value:=", "Offset_PMCore"],
   ["NAME:Pair", "Name:=", "Bridge",    "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "Rib",       "Value:=", "0mm"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCore",  "Value:=", "2"]]],
  ["NAME:Attributes",
   "Name:=", "1Magnet1S1_1_1",
   "Flags:=", "",
   "Color:=", "(0 212 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"N30UH_20C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
RotateObject("1Magnet1S1_1_1",270)


if float(oDesktop.GetVersion().split(".")[0]) < 2016:
  pass
else:
  oDesktop.ClearMessages(ModelName_ANSYSEM, "Motor-CAD cbh", 1)
oEditor.FitAll()

# Winding Groups 

# Winding Group WG_Ph1_P1
oBoundaryModule.AssignWindingGroup(["NAME:WG_Ph1_P1",
  "Type:=", "Current",
  "IsSolid:=", False,
  "Current:=", "IPeak * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 0 / 360 * 2 * pi) + PhaseAdvance )",
  "Resistance:=", "Rphase",
  "Inductance:=", "Lend * Is_2D_Design",
  "Voltage:=", "PeakDriveVoltage * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 0 / 360 * 2 * pi) + PhaseAdvance + PhasorAngle)",
  "ParallelBranchesNum:=", "ParallelPaths"])

# Winding Group WG_Ph2_P1
oBoundaryModule.AssignWindingGroup(["NAME:WG_Ph2_P1",
  "Type:=", "Current",
  "IsSolid:=", False,
  "Current:=", "IPeak * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 120 / 360 * 2 * pi) + PhaseAdvance )",
  "Resistance:=", "Rphase",
  "Inductance:=", "Lend * Is_2D_Design",
  "Voltage:=", "PeakDriveVoltage * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 120 / 360 * 2 * pi) + PhaseAdvance + PhasorAngle)",
  "ParallelBranchesNum:=", "ParallelPaths"])

# Winding Group WG_Ph3_P1
oBoundaryModule.AssignWindingGroup(["NAME:WG_Ph3_P1",
  "Type:=", "Current",
  "IsSolid:=", False,
  "Current:=", "IPeak * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 240 / 360 * 2 * pi) + PhaseAdvance )",
  "Resistance:=", "Rphase",
  "Inductance:=", "Lend * Is_2D_Design",
  "Voltage:=", "PeakDriveVoltage * sin((pi * MachineRPM/1rpm*NumPoles / 60*time - 240 / 360 * 2 * pi) + PhaseAdvance + PhasorAngle)",
  "ParallelBranchesNum:=", "ParallelPaths"])

# End Winding Definition

# Create Ansys armature coil Ph1_P1_C1
# From Slot 1 to Slot 5
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph1_P1_C1",
   "Flags:=", "",
   "Color:=", "(255 0 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph1_P1_C1",80)
# End of lap coil creation

# Create Ansys armature coil Ph1_P1_C2
# From Slot 2 to Slot 6
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph1_P1_C2",
   "Flags:=", "",
   "Color:=", "(255 0 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph1_P1_C2",100)
# End of lap coil creation

# Create Ansys armature coil Ph1_P1_C3
# From Slot 10 to Slot 6
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph1_P1_C3",
   "Flags:=", "",
   "Color:=", "(255 0 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph1_P1_C3",180)
# End of lap coil creation

# Create Ansys armature coil Ph1_P1_C6
# From Slot 1 to Slot 15
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph1_P1_C6",
   "Flags:=", "",
   "Color:=", "(255 0 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph1_P1_C6",0)
# End of lap coil creation

# Create Ansys armature coil Ph2_P1_C3
# From Slot 4 to Slot 18
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph2_P1_C3",
   "Flags:=", "",
   "Color:=", "(0 128 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph2_P1_C3",60)
# End of lap coil creation

# Create Ansys armature coil Ph2_P1_C4
# From Slot 4 to Slot 8
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph2_P1_C4",
   "Flags:=", "",
   "Color:=", "(0 128 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph2_P1_C4",140)
# End of lap coil creation

# Create Ansys armature coil Ph2_P1_C5
# From Slot 5 to Slot 9
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph2_P1_C5",
   "Flags:=", "",
   "Color:=", "(0 128 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph2_P1_C5",160)
# End of lap coil creation

# Create Ansys armature coil Ph2_P1_C6
# From Slot 13 to Slot 9
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph2_P1_C6",
   "Flags:=", "",
   "Color:=", "(0 128 0)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph2_P1_C6",240)
# End of lap coil creation

# Create Ansys armature coil Ph3_P1_C1
# From Slot 7 to Slot 11
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph3_P1_C1",
   "Flags:=", "",
   "Color:=", "(0 0 255)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph3_P1_C1",200)
# End of lap coil creation

# Create Ansys armature coil Ph3_P1_C2
# From Slot 8 to Slot 12
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph3_P1_C2",
   "Flags:=", "",
   "Color:=", "(0 0 255)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph3_P1_C2",220)
# End of lap coil creation

# Create Ansys armature coil Ph3_P1_C4
# From Slot 16 to Slot 2
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph3_P1_C4",
   "Flags:=", "",
   "Color:=", "(0 0 255)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph3_P1_C4",20)
# End of lap coil creation

# Create Ansys armature coil Ph3_P1_C5
# From Slot 17 to Slot 3
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph3_P1_C5",
   "Flags:=", "",
   "Color:=", "(0 0 255)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph3_P1_C5",40)
# End of lap coil creation

# Create Ansys armature coil Ph3_P1_C6
# From Slot 7 to Slot 3
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/LapCoil.dll", "Version:=", "16.0", "NoOfParameters:=", 22, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "80mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaStatorYoke"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "Stator_Lam_Length"],
  ["NAME:Pair", "Name:=", "Skew", "Value:=", "StatorSkewAngle"],
  ["NAME:Pair", "Name:=", "Slots", "Value:=", "SlotNumber_Stator"],
  ["NAME:Pair", "Name:=", "SlotType", "Value:=", "SlotType_Stator"],
  ["NAME:Pair", "Name:=", "Hs0", "Value:=", "Hs0_Stator"],
  ["NAME:Pair", "Name:=", "Hs1", "Value:=", "Hs1_Stator"],
  ["NAME:Pair", "Name:=", "Hs2", "Value:=", "15.2555195114007mm"],
  ["NAME:Pair", "Name:=", "Bs0", "Value:=", "Bs0_Stator"],
  ["NAME:Pair", "Name:=", "Bs1", "Value:=", "7.83290580686447mm"],
  ["NAME:Pair", "Name:=", "Bs2", "Value:=", "13.2128251960332mm"],
  ["NAME:Pair", "Name:=", "Rs", "Value:=", "Rs_Stator"],
  ["NAME:Pair", "Name:=", "FilletType", "Value:=", "FilletType_Stator"],
   ["NAME:Pair", "Name:=", "Layers", "Value:=", "Layers"],
   ["NAME:Pair", "Name:=", "CoilPitch", "Value:=", "-4"],
   ["NAME:Pair", "Name:=", "EndExt", "Value:=", "WdgExt_Avg"],
   ["NAME:Pair", "Name:=", "SpanExt", "Value:=", "SpanExt"],
   ["NAME:Pair", "Name:=", "BendAngle", "Value:=", "0deg"],
   ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle_Coil_Armature"],
   ["NAME:Pair", "Name:=", "LenRegion", "Value:=", "Model_Length"],
   ["NAME:Pair", "Name:=", "InfoCoil", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Ph3_P1_C6",
   "Flags:=", "",
   "Color:=", "(0 0 255)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"Copper (Pure)_40C\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Position the coil
RotateObject("Ph3_P1_C6",120)
# End of lap coil creation

# End of endwinding definition


# Assign Excitations
# Phase 1
# Assign excitations to Ph1_P1_C1
# Separate coil
SeparateCoil("Ph1_P1_C1", "255", "0", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C1_Ret",
  "Objects:=", ["Ph1_P1_C1_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Negative"])
# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C1_Go",
  "Objects:=", ["Ph1_P1_C1_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph1_P1_C1

# Assign excitations to Ph1_P1_C2
# Separate coil
SeparateCoil("Ph1_P1_C2", "255", "0", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C2_Ret",
  "Objects:=", ["Ph1_P1_C2_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Negative"])
# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C2_Go",
  "Objects:=", ["Ph1_P1_C2_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph1_P1_C2

# Assign excitations to Ph1_P1_C3
# Separate coil
SeparateCoil("Ph1_P1_C3", "255", "0", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C3_Ret",
  "Objects:=", ["Ph1_P1_C3_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Negative"])
# End of assign excitations to Ph1_P1_C3

# Assign excitations to Ph1_P1_C6
# Separate coil
SeparateCoil("Ph1_P1_C6", "255", "0", "0")

# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph1_P1_C6_Go",
  "Objects:=", ["Ph1_P1_C6_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph1",
  "ParentBndID:=", "WG_Ph1_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph1_P1_C6

# Phase 2
# Assign excitations to Ph2_P1_C3
# Separate coil
SeparateCoil("Ph2_P1_C3", "0", "128", "0")

# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C3_Go",
  "Objects:=", ["Ph2_P1_C3_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph2_P1_C3

# Assign excitations to Ph2_P1_C4
# Separate coil
SeparateCoil("Ph2_P1_C4", "0", "128", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C4_Ret",
  "Objects:=", ["Ph2_P1_C4_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Negative"])
# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C4_Go",
  "Objects:=", ["Ph2_P1_C4_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph2_P1_C4

# Assign excitations to Ph2_P1_C5
# Separate coil
SeparateCoil("Ph2_P1_C5", "0", "128", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C5_Ret",
  "Objects:=", ["Ph2_P1_C5_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Negative"])
# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C5_Go",
  "Objects:=", ["Ph2_P1_C5_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph2_P1_C5

# Assign excitations to Ph2_P1_C6
# Separate coil
SeparateCoil("Ph2_P1_C6", "0", "128", "0")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph2_P1_C6_Ret",
  "Objects:=", ["Ph2_P1_C6_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph2",
  "ParentBndID:=", "WG_Ph2_P1",
  "PolarityType:=", "Negative"])
# End of assign excitations to Ph2_P1_C6

# Phase 3
# Assign excitations to Ph3_P1_C1
# Separate coil
SeparateCoil("Ph3_P1_C1", "0", "0", "255")

# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C1_Go",
  "Objects:=", ["Ph3_P1_C1_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph3_P1_C1

# Assign excitations to Ph3_P1_C2
# Separate coil
SeparateCoil("Ph3_P1_C2", "0", "0", "255")

# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C2_Go",
  "Objects:=", ["Ph3_P1_C2_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Positive"])
# End of assign excitations to Ph3_P1_C2

# Assign excitations to Ph3_P1_C4
# Separate coil
SeparateCoil("Ph3_P1_C4", "0", "0", "255")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C4_Ret",
  "Objects:=", ["Ph3_P1_C4_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Negative"])
# End of assign excitations to Ph3_P1_C4

# Assign excitations to Ph3_P1_C5
# Separate coil
SeparateCoil("Ph3_P1_C5", "0", "0", "255")

# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C5_Ret",
  "Objects:=", ["Ph3_P1_C5_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Negative"])
# End of assign excitations to Ph3_P1_C5

# Assign excitations to Ph3_P1_C6
# Separate coil
SeparateCoil("Ph3_P1_C6", "0", "0", "255")

# Assign excitation to Go end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C6_Go",
  "Objects:=", ["Ph3_P1_C6_1"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Positive"])
# Assign excitation to Ret end
oBoundaryModule.AssignCoil(["NAME:CT_Ph3_P1_C6_Ret",
  "Objects:=", ["Ph3_P1_C6_2"],
  "Conductor number:=",50,
  "Winding:=", "Ph3",
  "ParentBndID:=", "WG_Ph3_P1",
  "PolarityType:=", "Negative"])
# End of assign excitations to Ph3_P1_C6


# Create magnets and set mag directions
CreateMagnetCoordinateSystem("1Magnet1N1_1_1",
  "34.0086459538797", "16.4132202994941", "0",
  "0.795495128834866", "0.795495128834866",
  "-0.795495128834866", "0.795495128834866",
  0)

CreateMagnetCoordinateSystem("1Magnet1S2_1_1",
  "-16.4132202994941", "34.0086459538797", "0",
  "0.795495128834866", "-0.795495128834866",
  "0.795495128834866", "0.795495128834866",
  0)

CreateMagnetCoordinateSystem("1Magnet1N2_1_1",
  "-34.0086459538797", "-16.4132202994941", "0",
  "-0.795495128834866", "-0.795495128834866",
  "0.795495128834866", "-0.795495128834866",
  0)

CreateMagnetCoordinateSystem("1Magnet1S1_1_1",
  "16.413220299494", "-34.0086459538797", "0",
  "-0.795495128834866", "0.795495128834866",
  "-0.795495128834866", "-0.795495128834866",
  0)


oEditor.SetWCS(["NAME:SetWCS Parameter", "Working Coordinate System:=", "Global"])

# Set region temperatures
oDesign.SetObjectTemperature(["NAME:TemperatureSettings",
  "IncludeTemperatureDependence:=", True,
  "EnableFeedback:=", False,
  "Temperatures:=", [
   "1Magnet1N1_1_1", "20cel",
   "1Magnet1S2_1_1", "20cel",
   "1Magnet1N2_1_1", "20cel",
   "1Magnet1S1_1_1", "20cel"]]
)

modelLength_Axial = 0
# Reset the global CS
oEditor.SetWCS(["NAME:SetWCS Parameter",
  "Working Coordinate System:=", "Global",
  "RegionDepCSOk:=", False])

  
# Rotating_Band
oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/Band.dll", "Version:=", "12.1", "NoOfParameters:=", 7, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "DiaGap - (2 * (Airgap - Banding_Thickness)) + (4 * ((airgap - Banding_Thickness - Sleeve_Thickness) / 4))"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "Shaft_Hole_Diameter"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", str(modelLength_Axial).replace(",", ".") + "mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "0deg"],
  ["NAME:Pair", "Name:=", "Fractions", "Value:=", "SymmetryFactor"],
  ["NAME:Pair", "Name:=", "HalfAxial", "Value:=", "HalfAxial"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "0"]]],
  ["NAME:Attributes",
   "Name:=", "Rotating_Band",
   "Flags:=", "",
   "Color:=", "(143 175 143)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"vacuum\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Create outer band Regions

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/Band.dll", "Version:=", "12.1", "NoOfParameters:=", 7, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "1mm"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaOuter"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", str(modelLength_Axial).replace(",", ".") + "mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle"],
  ["NAME:Pair", "Name:=", "Fractions", "Value:=", "SymmetryFactor"],
  ["NAME:Pair", "Name:=", "HalfAxial", "Value:=", "HalfAxial"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "1"]]],
  ["NAME:Attributes",
   "Name:=", "Band_Tool",
   "Flags:=", "",
   "Color:=", "(143 175 143)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"vacuum\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/Band.dll", "Version:=", "12.1", "NoOfParameters:=", 7, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "DiaGap+Airgap"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaOuter"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", str(modelLength_Axial).replace(",", ".") + "mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle"],
  ["NAME:Pair", "Name:=", "Fractions", "Value:=", "SymmetryFactor"],
  ["NAME:Pair", "Name:=", "HalfAxial", "Value:=", "HalfAxial"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "100"]]],
  ["NAME:Attributes",
   "Name:=", "Whole_Region",
   "Flags:=", "",
   "Color:=", "(143 175 143)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"vacuum\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)
oBoundaryModule.SetCoreLoss(["Stator_Lamination_Primitive", "Rotor_Lamination_Primitive"], False)

# Start of Eddy Effects Setup
oBoundaryModule.SetEddyEffect(["NAME:Eddy Effect Setting", ["NAME:EddyEffectVector",
  ["NAME:Data", "Object Name:=", "Armature_Winding_1", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_2", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_3", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_4", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_5", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_6", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_7", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_8", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "Armature_Winding_9", "Eddy Effect:=", False],
  ["NAME:Data", "Object Name:=", "1Magnet1N1_1_1", "Eddy Effect:=", True],
  ["NAME:Data", "Object Name:=", "1Magnet1S2_1_1", "Eddy Effect:=", True],
  ["NAME:Data", "Object Name:=", "1Magnet1N2_1_1", "Eddy Effect:=", True],
  ["NAME:Data", "Object Name:=", "1Magnet1S1_1_1", "Eddy Effect:=", True]]]
)
# End of Eddy Effects Setup

# Subtract band tool
BandToolSubtraction("Band_Tool")

# Reset the global CS
oEditor.SetWCS(["NAME:SetWCS Parameter",
  "Working Coordinate System:=", "Global",
  "RegionDepCSOk:=", False])


# Motion and Boundaries Setup

# WriteOuterBoundary
edgeid = oEditor.GetEdgeByPosition(["NAME:EdgeParameters",
  "BodyName:=", "Whole_Region",
  "XPosition:=", "0mm",
  "YPosition:=", "65mm",
  "ZPosition:=", "0mm"])
oBoundaryModule.AssignVectorPotential(["NAME:VectorPotential1",
  "Edges:=", [edgeid],
  "Value:=", "0",
  "CoordinateSystem:=", ""])
# End of WriteOuterBoundary
# End of Motion and Boundaries Setup
# Reset the global CS
oEditor.SetWCS(["NAME:SetWCS Parameter",
  "Working Coordinate System:=", "Global",
  "RegionDepCSOk:=", False]
)

# Independent Boundary

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/Band.dll", "Version:=", "12.1", "NoOfParameters:=", 7, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "DiaGap+Airgap"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaOuter"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle"],
  ["NAME:Pair", "Name:=", "Fractions", "Value:=", "SymmetryFactor"],
  ["NAME:Pair", "Name:=", "HalfAxial", "Value:=", "HalfAxial"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "2"]]],
  ["NAME:Attributes",
   "Name:=", "Boundary_Independent",
   "Flags:=", "",
   "Color:=",  "(143 175 143)",
   "Transparency:=", 0.8,
   "PartCoordinateSystem:=", "Global",
   "UDMId:=", "",
   "MaterialValue:=", "\"vacuum\"",
   "SurfaceMaterialValue:=", "\"\"",
   "SolveInside:=", True,
   "IsMaterialEditable:=", True,
   "UseMaterialAppearance:=", False]
)

# Dependent Boundary

oEditor.CreateUserDefinedPart(["NAME:UserDefinedPrimitiveParameters", "DllName:=",
  "RMxprt/Band.dll", "Version:=", "12.1", "NoOfParameters:=", 7, "Library:=",
  "syslib", ["NAME:ParamVector",
  ["NAME:Pair", "Name:=", "DiaGap", "Value:=", "DiaGap+Airgap"],
  ["NAME:Pair", "Name:=", "DiaYoke", "Value:=", "DiaOuter"],
  ["NAME:Pair", "Name:=", "Length", "Value:=", "0mm"],
  ["NAME:Pair", "Name:=", "SegAngle", "Value:=", "SegAngle"],
  ["NAME:Pair", "Name:=", "Fractions", "Value:=", "SymmetryFactor"],
  ["NAME:Pair", "Name:=", "HalfAxial", "Value:=", "HalfAxial"],
  ["NAME:Pair", "Name:=", "InfoCore", "Value:=", "3"]]],
  ["NAME:Attributes",
    "Name:=", "Boundary_Dependent",
    "Flags:=", "",
    "Color:=", "(143 175 143)",
    "Transparency:=", 0.8,
    "PartCoordinateSystem:=", "Global",
    "UDMId:=", "",
    "MaterialValue:=", "\"vacuum\"",
    "SurfaceMaterialValue:=", "\"\"",
    "SolveInside:=", True,
    "IsMaterialEditable:=", True,
    "UseMaterialAppearance:=", False]
)


# Assign boundaries setup - Independent/Dependent
oBoundaryModule.AssignMaster(["NAME:Independent1",
  "Objects:=", ["Boundary_Independent"],
  ["NAME:CoordSysVector",
   "Origin:=", ["0mm", "0mm", "0mm"],
   "UPos:=", ["65mm", "0mm", "0mm"]],
  "ReverseU:=", False]
)
# Bs = Bm for this model

oBoundaryModule.AssignSlave(["NAME:Dependent1",
  "Objects:=", ["Boundary_Dependent"],
  ["NAME:CoordSysVector",
   "Origin:=", ["0mm", "0mm", "0mm"],
   "UPos:=", ["-65mm", "0mm", "0mm"]],
    "ReverseU:=", False,
    "Master:=", "Independent1",
    "SameAsMaster:=", True,
    "RelationIsSame:=", True]
)


# Delete unclassified objects
oObjects = oEditor.GetObjectsInGroup("Unclassified")
for oObject in oObjects:
  oEditor.Delete(["NAME:Selections", "Selections:=", oObject])


# Motion setup
oModelModule.AssignBand(["NAME:Data",
  "Move Type:=", "Rotate",
  "Coordinate System:=", "Global",
  "Axis:=", "Z",
  "Is Positive:=", True,
  "InitPos:=", "InitialPositionMD",
  "HasRotateLimit:=", False,
  "NonCylindrical:=", False,
  "Consider Mechanical Transient:=", False,
  "Angular Velocity:=", "MachineRPM",
  "Objects:=", ["Rotating_Band"]]
)
if versionArray[0] > 2023 or (versionArray[0] == 2023 and versionArray[1] >= 2):
  oMeshModule.EditCylindricalGapOp("CylindricalGap1",
    ["NAME:CylindricalGap1",
     "UseBandMappingAngle:=", True,
     "BandMappingAngle:=", "(360/360) deg"])
versionArray = oDesktop.GetVersion().split(".")
if versionArray[0] <= 2021 and versionArray[1] < 2:
  oDesign.SetDesignSettings(["NAME:Design Settings Data",
    "Allow Material Override:=",   False,
    "Perform Minimal validation:=", False,
    "EnabledObjects:=", [],
    "PreserveTranSolnAfterDatasetEdit:=", False,
    "ComputeTransientInductance:=", False,
    "ComputeIncrementalMatrix:=", False,
    "PerfectConductorThreshold:=", 1E+030,
    "InsulatorThreshold:=", 1,
  "UseSkewModel:=", False,
  "EnableTranTranLinkWithSimplorer:=", False,
  "ModelDepth:=", "Magnetic_Axial_Length",
  "Multiplier:=", "SymmetryFactor*(1+HalfAxial)"],
  ["NAME:Model Validation Settings",
   "EntityCheckLevel:=", "Strict",
   "IgnoreUnclassifiedObjects:=", True,
    "SkipIntersectionChecks:=", False]
)
else:
  oDesign.SetDesignSettings(["NAME:Design Settings Data",
    "Allow Material Override:=",   False,
    "Perform Minimal validation:=", False,
    "EnabledObjects:=", [],
    "PreserveTranSolnAfterDatasetEdit:=", False,
    "ComputeTransientInductance:=", False,
    "ComputeIncrementalMatrix:=", False,
    "PerfectConductorThreshold:=", 1E+030,
    "InsulatorThreshold:=", 1,
  "UseSkewModel:=", False,
  "EnableTranTranLinkWithSimplorer:=", False,
  "ModelDepth:=", "Magnetic_Axial_Length",
  "Multiplier:=", "SymmetryFactor*(1+HalfAxial)"],
  ["NAME:Model Validation Settings",
   "EntityCheckLevel:=", "Strict",
   "IgnoreUnclassifiedObjects:=", True,
    "SkipIntersectionChecks:=", False]
)

# Start of Analysis Setup - 2D
oAnalysisModule.InsertSetup("Transient",
  ["NAME:Setup1",
   "Enabled:=", True,
   "NonlinearSolverResidual:=", "0.0001",
   "TimeIntegrationMethod:=", 0,
   "StopTime:=", "NumTorqueCycles*120/(MachineRPM/1rpm*NumPoles) s",
   "TimeStep:=", "120/(MachineRPM/1rpm*NumPoles)/NumTorquePointsPerCycle s",
   "OutputError:=", False,
   "UseControlProgram:=", False,
   "ControlProgramName:=", " ",
   "ControlProgramArg:=", " ",
   "CallCtrlProgAfterLastStep:=", False,
   "OutputPerObjectCoreLoss:=", True,
   "OutputPerObjectSolidLoss:=", True,
   "SaveFieldsType:=", "None",
   ["NAME:HcOption",
    "TransientHcNonLinearBH:=", True,
    "TransientComputeHc:=",  False,
    "ComputeHcFromBhCurve:=", True],
   "UseAdaptiveTimeStep:=", False,
   "InitialTimeStep:=",  "120/(MachineRPM/1rpm*NumPoles)/NumTorquePointsPerCycle s",
   "MinTimeStep:=", "0.001s",
   "MaxTimeStep:=", "0.003s",
   "TimeStepErrTolerance:=", 0.0001]
)
# End of Analysis Setup

# Set as default mesh - classic
oMeshModule.InitialMeshSettings(["NAME:MeshSettings",
  ["NAME:GlobalSurfApproximation",
   "CurvedSurfaceApproxChoice:=","UseSlider",
   "SliderMeshSettings:=", 5],
  ["NAME:GlobalCurvilinear",
   "Apply:=", False],
  ["NAME:GlobalModelRes",
   "UseAutoLength:=", True],
  "MeshMethod:=", "AnsoftTAU",
  "UseLegacyFaceterForTauVolumeMesh:=", False]
)

# Start of Report Setup

CreateOutputVariable("ThetaED", "((pi * MachineRPM/1rpm*NumPoles / 60*time - 0 / 360 * 2 * pi)) + pi")
CreateOutputVariable("Id_peak", "2/3*(InputCurrent(WG_Ph1_P1)*cos(ThetaED)+InputCurrent(WG_Ph2_P1)*cos(ThetaED - 120deg)+InputCurrent(WG_Ph3_P1)*cos(ThetaED - 240deg))")
CreateOutputVariable("Iq_peak", "2/3*(InputCurrent(WG_Ph1_P1)*-sin(ThetaED)+InputCurrent(WG_Ph2_P1)*-sin(ThetaED - 120deg)+InputCurrent(WG_Ph3_P1)*-sin(ThetaED - 240deg))")
CreateOutputVariable("PsiD", "2/3*(FluxLinkage(WG_Ph1_P1)*cos(ThetaED)+FluxLinkage(WG_Ph2_P1)*cos(ThetaED - 120deg)+FluxLinkage(WG_Ph3_P1)*cos(ThetaED - 240deg))")
CreateOutputVariable("PsiQ", "2/3*(FluxLinkage(WG_Ph1_P1)*-sin(ThetaED)+FluxLinkage(WG_Ph2_P1)*-sin(ThetaED - 120deg)+FluxLinkage(WG_Ph3_P1)*-sin(ThetaED - 240deg))")
CreateOutputVariable("TorqueDQ", "3/2*NumPoles/2*(PsiD*Iq_peak - PsiQ*Id_peak)")

oReportModule.CreateReport("Induced Voltage Plots",
  "Transient", "Rectangular Plot",
  "Setup1 : Transient", ["Domain:=", "Sweep"], ["Time:=", ["All"],
  "IPeak:=", ["Nominal"],
  "PhaseAdvance:=", ["Nominal"],
  "NumTorqueCycles:=", ["Nominal"],
  "NumTorquePointsPerCycle:=", ["Nominal"],
  "MachineRPM:=", ["Nominal"],
  "NumPoles:=", ["Nominal"],
  "DriveOffsetED:=", ["Nominal"]],
  ["X Component:=", "Time",
   "Y Component:=", ["InducedVoltage(WG_Ph1_P1)","InducedVoltage(WG_Ph2_P1)","InducedVoltage(WG_Ph3_P1)"]],
  []
  )
oReportModule.AddTraceCharacteristics("Induced Voltage Plots", "min", [], ["Full"])
oReportModule.AddTraceCharacteristics("Induced Voltage Plots", "avg", [], ["Full"])
oReportModule.AddTraceCharacteristics("Induced Voltage Plots", "max", [], ["Full"])

oReportModule.CreateReport("Drive Current Plots",
  "Transient", "Rectangular Plot",
  "Setup1 : Transient", ["Domain:=", "Sweep"], ["Time:=", ["All"],
  "IPeak:=", ["Nominal"],
  "PhaseAdvance:=", ["Nominal"],
  "NumTorqueCycles:=", ["Nominal"],
  "NumTorquePointsPerCycle:=", ["Nominal"],
  "MachineRPM:=", ["Nominal"],
  "NumPoles:=", ["Nominal"],
  "DriveOffsetED:=", ["Nominal"]],
  ["X Component:=", "Time",
   "Y Component:=", ["InputCurrent(WG_Ph1_P1)", "InputCurrent(WG_Ph2_P1)", "InputCurrent(WG_Ph3_P1)", "Id_peak", "Iq_peak"]],
  []
  )
oReportModule.AddTraceCharacteristics("Drive Current Plots", "min", [], ["Full"])
oReportModule.AddTraceCharacteristics("Drive Current Plots", "avg", [], ["Full"])
oReportModule.AddTraceCharacteristics("Drive Current Plots", "max", [], ["Full"])

oReportModule.ChangeProperty(["NAME:AllTabs", ["NAME:Trace",
  ["NAME:PropServers", "Drive Current Plots:Id_peak"],
  ["NAME:ChangedProps",
   ["NAME:Y Axis", "Value:=", "Y1"]]]])
oReportModule.ChangeProperty(["NAME:AllTabs", ["NAME:Trace",
  ["NAME:PropServers", "Drive Current Plots:Iq_peak"],
  ["NAME:ChangedProps",
   ["NAME:Y Axis", "Value:=", "Y1"]]]])
oReportModule.CreateReport("Flux Linkage Plots",
  "Transient", "Rectangular Plot",
  "Setup1 : Transient", ["Domain:=", "Sweep"], ["Time:=", ["All"],
  "IPeak:=", ["Nominal"],
  "PhaseAdvance:=", ["Nominal"],
  "NumTorqueCycles:=", ["Nominal"],
  "NumTorquePointsPerCycle:=", ["Nominal"],
  "MachineRPM:=", ["Nominal"],
  "NumPoles:=", ["Nominal"],
  "DriveOffsetED:=", ["Nominal"]],
  ["X Component:=", "Time",
   "Y Component:=", ["FluxLinkage(WG_Ph1_P1)", "FluxLinkage(WG_Ph2_P1)", "FluxLinkage(WG_Ph3_P1)", "PsiD", "PsiQ"]],
  []
  )
oReportModule.AddTraceCharacteristics("Flux Linkage Plots", "min", [], ["Full"])
oReportModule.AddTraceCharacteristics("Flux Linkage Plots", "avg", [], ["Full"])
oReportModule.AddTraceCharacteristics("Flux Linkage Plots", "max", [], ["Full"])

oReportModule.ChangeProperty(["NAME:AllTabs", ["NAME:Trace",
  ["NAME:PropServers", "Flux Linkage Plots:PsiD"],
  ["NAME:ChangedProps",
   ["NAME:Y Axis", "Value:=", "Y1"]]]])
oReportModule.ChangeProperty(["NAME:AllTabs", ["NAME:Trace",
  ["NAME:PropServers", "Flux Linkage Plots:PsiQ"],
  ["NAME:ChangedProps",
   ["NAME:Y Axis", "Value:=", "Y1"]]]])
oReportModule.CreateReport("Torque Plots",
  "Transient", "Rectangular Plot",
  "Setup1 : Transient", ["Domain:=", "Sweep"], ["Time:=", ["All"],
  "IPeak:=", ["Nominal"],
  "PhaseAdvance:=", ["Nominal"],
  "NumTorqueCycles:=", ["Nominal"],
  "NumTorquePointsPerCycle:=", ["Nominal"],
  "MachineRPM:=", ["Nominal"],
  "NumPoles:=", ["Nominal"],
  "DriveOffsetED:=", ["Nominal"]],
  ["X Component:=", "Time",
   "Y Component:=", ["Moving1.Torque", "TorqueDQ"]],
  []
  )
oReportModule.AddTraceCharacteristics("Torque Plots", "min", [], ["Full"])
oReportModule.AddTraceCharacteristics("Torque Plots", "avg", [], ["Full"])
oReportModule.AddTraceCharacteristics("Torque Plots", "max", [], ["Full"])

oReportModule.ChangeProperty(["NAME:AllTabs", ["NAME:Scaling",
  ["NAME:PropServers", "Torque Plots:AxisY1"],
  ["NAME:ChangedProps",
   ["NAME:Min", "Value:=", "0.0NewtonMeter"]]]])

oReportModule.ChangeProperty(["NAME:AllTabs",
  ["NAME:Trace",
   ["NAME:PropServers", "Torque Plots:TorqueDQ"],
   ["NAME:ChangedProps", ["NAME:Y Axis", "Value:=", "Y1"]]]])

# End of Report Setup
oEditor.FitAll()


oProject.Save()
# Validate the model and send results to text file
oDesign.ValidateDesign("d:\\KangDH\\Emlab_emach\\tools\\ansys\\" + ModelName + ".txt")

oDesktop.EnableAutoSave(autoSaveConfig)
# Stop Python scripting environment -- needs to be called at the end
ScriptEnv.Shutdown()
