"""pyMCAD helpers extracted from notebooks (tools tree).

This is the preferred location for notebook-facing utilities.
"""

from .stress import (  # noqa: F401
	StressElement,
	StressRegion,
	StressRegions,
	check_youngs_modulus,
	find_divergence_point,
	get_stress_data,
	get_stress_data_from_file,
	mcad_default_export_dir,
	mcad_make_temp_txt_path,
	interactive_mesh_stress_fields_plot,
	plot_mesh_stress_fields,
	temperature_adjusted_curve,
)

from .magnetic import (  # noqa: F401
	MagElement,
	MagneticRegion,
	MagneticRegions,
	MagneticRegionsTimeSeries,
	get_magnetic_data,
	get_magnetic_data_from_file,
	get_magnetic_timeseries_from_file,
	interactive_magnetic_plot,
	interactive_magnetic_quiver,
)

from .b_locus import (  # noqa: F401
	interactive_b_locus_field_plot,
)

from .loss import (  # noqa: F401
	ElementMesh,
	ElementRecord,
	ElementScalarField,
	get_element_loss_fields,
	interactive_loss_fields_plot,
)

from .melec_req_check import (  # noqa: F401
	calc_motorcad_lab_base_point_from_mat,
	calc_motorcad_lab_base_point_spm_phase0_from_mat,
	debug_motorlab_angle_keys,
	df_to_mcad_variables,
	get_mcad_variables,
	get_back_emf_metrics,
	make_limit_df,
	overlay_speed_torque_limit_points_on_effimap,
	plotNrunMCADLab,
	plot_back_emf_waveforms,
	plot_cogging_torque_waveform,
	plot_currents_waveforms,
	plot_fea_path_graph_waveform,
	plot_speed_torque_limit_overlay,
	plot_flux_linkage_waveforms,
	plot_graph_waveform,
	plot_multi_graph_waveforms,
	plot_terminal_voltage_waveform,
	plot_torque_vw_waveform,
	read_csv_with_encoding_autodetect,
	set_mcad_variables,
	style_axes,
	list_graph_names_from_ini,
	get_graph_type_map_from_ini,
	get_graph_xy_from_ini,
)

from .dxf_geometry import (  # noqa: F401
	dxf_entitylists_to_regions,
	dxf_to_ir,
	dxf_to_entitylists,
	dxf_to_regions,
	force_black_white,
	get_dxf_layer_summary,
	get_dxf_region_layer_map,
	guess_dxf_regions_from_layer_names,
	ir_to_motorcad_regions,
	infer_region_type_from_layer_name,
	interactive_regions_viewer,
	plot_dxf_black_white,
	plot_dxf_layers_black_white,
	regions_summary_df,
)

from .thermal import (  # noqa: F401
	ThermalElement,
	ThermalRegion,
	ThermalRegions,
	get_thermal_data,
	get_thermal_data_from_file,
	interactive_mesh_thermal_fields_plot,
	plot_mesh_thermal_fields,
)

__all__ = [
	"MagElement",
	"MagneticRegion",
	"MagneticRegions",
	"MagneticRegionsTimeSeries",
	"get_magnetic_data",
	"get_magnetic_data_from_file",
	"get_magnetic_timeseries_from_file",
	"interactive_magnetic_plot",
	"interactive_magnetic_quiver",
	"interactive_b_locus_field_plot",
	"StressElement",
	"StressRegion",
	"StressRegions",
	"ElementMesh",
	"ElementRecord",
	"ElementScalarField",
	"get_element_loss_fields",
	"interactive_loss_fields_plot",
	"ThermalElement",
	"ThermalRegion",
	"ThermalRegions",
	"get_thermal_data",
	"get_thermal_data_from_file",
	"plot_mesh_thermal_fields",
	"check_youngs_modulus",
	"make_limit_df",
	"style_axes",
	"plot_speed_torque_limit_overlay",
	"read_csv_with_encoding_autodetect",
	"df_to_mcad_variables",
	"get_mcad_variables",
	"set_mcad_variables",
	"plot_dxf_black_white",
	"get_dxf_layer_summary",
	"guess_dxf_regions_from_layer_names",
	"get_dxf_region_layer_map",
	"plot_dxf_layers_black_white",
	"dxf_to_entitylists",
	"dxf_to_ir",
	"dxf_entitylists_to_regions",
	"infer_region_type_from_layer_name",
	"dxf_to_regions",
	"ir_to_motorcad_regions",
	"regions_summary_df",
	"interactive_regions_viewer",
	"plotNrunMCADLab",
	"get_back_emf_metrics",
	"plot_back_emf_waveforms",
	"plot_cogging_torque_waveform",
	"plot_torque_vw_waveform",
	"list_graph_names_from_ini",
	"get_graph_type_map_from_ini",
	"get_graph_xy_from_ini",
	"plot_graph_waveform",
	"plot_multi_graph_waveforms",
	"plot_currents_waveforms",
	"plot_terminal_voltage_waveform",
	"plot_flux_linkage_waveforms",
	"plot_fea_path_graph_waveform",
	"overlay_speed_torque_limit_points_on_effimap",
	"calc_motorcad_lab_base_point_from_mat",
	"calc_motorcad_lab_base_point_spm_phase0_from_mat",
	"debug_motorlab_angle_keys",
	"find_divergence_point",
	"get_stress_data",
	"get_stress_data_from_file",
	"mcad_default_export_dir",
	"mcad_make_temp_txt_path",
	"interactive_mesh_stress_fields_plot",
	"plot_mesh_stress_fields",
	"temperature_adjusted_curve",
	"interactive_mesh_thermal_fields_plot",
	"plot_mesh_thermal_fields",
]
