
"""pyMCAD helpers extracted from notebooks (tools tree).

This is the preferred location for notebook-facing utilities.
"""

from importlib.util import find_spec

from .magnetic import (  # noqa: F401
	MagElement,
	MagneticRegion,
	MagneticRegions,
	MagneticRegionsTimeSeries,
	export_magnetic_txt,
	export_magnetic_snapshot_svgs,
	export_magnetic_timeseries_gif,
	export_magnetic_timeseries_h5,
	export_magnetic_snapshot_h5,
	inspect_magnetic_timeseries_h5,
	read_magnetic_h5_format,
	diagnose_magnetic_h5_mesh_motion,
	load_magnetic_timeseries_h5_arrays,
	load_magnetic_timeseries_h5_datasets,
	load_magnetic_snapshot_h5_arrays,
	get_magnetic_data,
	get_magnetic_data_from_file,
	get_magnetic_timeseries_from_file,
	interactive_magnetic_plot,
	interactive_magnetic_quiver,
)

from .b_locus import (  # noqa: F401
	interactive_b_locus_field_plot,
)

from .loss import (  # noqa: F401
	ElementMesh,
	ElementRecord,
	ElementScalarField,
	export_element_loss_txt,
	export_loss_svgs,
	get_element_loss_fields,
	get_element_loss_fields_from_file,
	interactive_loss_fields_plot,
)

from ._export import (  # noqa: F401
	mcad_default_export_dir,
	mcad_make_temp_txt_path,
)

from .stress import (  # noqa: F401
	StressElement,
	StressRegion,
	StressRegions,
	check_youngs_modulus,
	export_stress_txt,
	export_stress_svgs,
	find_divergence_point,
	get_stress_data,
	get_stress_data_from_file,
	interactive_mesh_stress_fields_plot,
	plot_mesh_stress_fields,
	temperature_adjusted_curve,
)

from .thermal import (  # noqa: F401
	ThermalElement,
	ThermalRegion,
	ThermalRegions,
	export_thermal_txt,
	export_thermal_svgs,
	get_thermal_data,
	get_thermal_data_from_file,
	interactive_mesh_thermal_fields_plot,
	plot_mesh_thermal_fields,
)

from .melec_req_check import (  # noqa: F401
	calc_motorcad_lab_base_point_from_mat,
	calc_motorcad_lab_base_point_spm_phase0_from_mat,
	debug_motorlab_angle_keys,
	df_to_mcad_variables,
	get_back_emf_metrics,
	get_graph_type_map_from_ini,
	get_graph_xy_from_ini,
	list_graph_names_from_ini,
	get_mcad_variables,
	make_limit_df,
	overlay_speed_torque_limit_points_on_effimap,
	plotNrunMCADLab,
	plot_back_emf_waveforms,
	plot_cogging_torque_waveform,
	plot_currents_waveforms,
	plot_fea_path_graph_waveform,
	plot_flux_linkage_waveforms,
	plot_graph_waveform,
	plot_multi_graph_waveforms,
	plot_speed_torque_limit_overlay,
	plot_terminal_voltage_waveform,
	plot_torque_vw_waveform,
	read_csv_with_encoding_autodetect,
	set_mcad_variables,
	style_axes,
)

from .dxf_geometry import (  # noqa: F401
	dxf_entitylists_to_regions,
	dxf_to_entitylists,
	dxf_to_ir,
	dxf_to_regions,
	get_dxf_layer_summary,
	get_dxf_region_layer_map,
	guess_dxf_regions_from_layer_names,
	infer_region_type_from_layer_name,
	interactive_regions_viewer,
	ir_to_motorcad_regions,
	plot_dxf_black_white,
	plot_dxf_layers_black_white,
	regions_summary_df,
)

from .results import (  # noqa: F401
	DEFAULT_MES_KIND_ALIASES,
	find_latest_mes,
	find_latest_mes_by_kind,
	list_mes_files,
)

from .fea_workflow import (  # noqa: F401
	FEAExportSession,
	FEAProcessResult,
	orchestrate_fea_export,
	prepare_fea_export_session,
	process_fea_result_from_mes,
)

from .mes_backup import (  # noqa: F401
	EXPORT_COLUMNS,
	export_mes_to_txt,
	find_all_backup_mes_files,
	find_backup_mes_files,
	find_backup_roots,
)

_HAS_DOE_BATCH = find_spec(__name__ + ".doe_batch") is not None
if _HAS_DOE_BATCH:
	from .doe_batch import (  # noqa: F401
		DOESolveResult,
		DOEExportResult,
		doe_solve_single,
		doe_export_txt,
		doe_export_txt_from_saved,
		doe_export_h5_from_txt,
		doe_export_h5,
		doe_batch_run,
		doe_h5_batch_from_txt,
		doe_export_from_saved,
		doe_scan_status,
		doe_repair_missing_txt,
	)

from .winding_auto import (  # noqa: F401
	auto_resize_copper_after_geometry_update,
)

from .scaling import (  # noqa: F401
	ScalingFactor,
	MotorCADGeo,
	ScaledMachineData,
	scale_resistance_by_temp,
	calc_current_density,
	parse_mcad_colon_str,
	def_scaling_factor,
	get_mcad_machine_data,
	get_mcad_building_data,
	sl_scale_machine,
	apply_scaled_data_to_mcad,
)

__all__ = [
	"MagElement",
	"MagneticRegion",
	"MagneticRegions",
	"MagneticRegionsTimeSeries",
	"export_magnetic_txt",
	"export_magnetic_snapshot_svgs",
	"export_magnetic_timeseries_gif",
	"export_magnetic_timeseries_h5",
	"export_magnetic_snapshot_h5",
	"inspect_magnetic_timeseries_h5",
	"read_magnetic_h5_format",
	"diagnose_magnetic_h5_mesh_motion",
	"load_magnetic_timeseries_h5_arrays",
	"load_magnetic_timeseries_h5_datasets",
	"load_magnetic_snapshot_h5_arrays",
	"get_magnetic_data",
	"get_magnetic_data_from_file",
	"get_magnetic_timeseries_from_file",
	"interactive_magnetic_plot",
	"interactive_magnetic_quiver",
	"interactive_b_locus_field_plot",
	"StressElement",
	"StressRegion",
	"StressRegions",
	"ElementMesh",
	"ElementRecord",
	"ElementScalarField",
	"export_element_loss_txt",
	"export_loss_svgs",
	"get_element_loss_fields",
	"get_element_loss_fields_from_file",
	"interactive_loss_fields_plot",
	"ThermalElement",
	"ThermalRegion",
	"ThermalRegions",
	"export_thermal_txt",
	"export_thermal_svgs",
	"get_thermal_data",
	"get_thermal_data_from_file",
	"interactive_mesh_thermal_fields_plot",
	"plot_mesh_thermal_fields",
	"check_youngs_modulus",
	"make_limit_df",
	"style_axes",
	"plot_speed_torque_limit_overlay",
	"read_csv_with_encoding_autodetect",
	"df_to_mcad_variables",
	"get_mcad_variables",
	"set_mcad_variables",
	"plot_dxf_black_white",
	"get_dxf_layer_summary",
	"guess_dxf_regions_from_layer_names",
	"get_dxf_region_layer_map",
	"plot_dxf_layers_black_white",
	"dxf_to_entitylists",
	"dxf_to_ir",
	"dxf_entitylists_to_regions",
	"infer_region_type_from_layer_name",
	"dxf_to_regions",
	"ir_to_motorcad_regions",
	"regions_summary_df",
	"interactive_regions_viewer",
	"plotNrunMCADLab",
	"get_back_emf_metrics",
	"plot_back_emf_waveforms",
	"plot_cogging_torque_waveform",
	"plot_torque_vw_waveform",
	"list_graph_names_from_ini",
	"get_graph_type_map_from_ini",
	"get_graph_xy_from_ini",
	"plot_graph_waveform",
	"plot_multi_graph_waveforms",
	"plot_currents_waveforms",
	"plot_terminal_voltage_waveform",
	"plot_flux_linkage_waveforms",
	"plot_fea_path_graph_waveform",
	"overlay_speed_torque_limit_points_on_effimap",
	"calc_motorcad_lab_base_point_from_mat",
	"calc_motorcad_lab_base_point_spm_phase0_from_mat",
	"debug_motorlab_angle_keys",
	"find_divergence_point",
	"export_stress_txt",
	"get_stress_data",
	"get_stress_data_from_file",
	"mcad_default_export_dir",
	"mcad_make_temp_txt_path",
	"interactive_mesh_stress_fields_plot",
	"plot_mesh_stress_fields",
	"export_stress_svgs",
	"temperature_adjusted_curve",
	"DEFAULT_MES_KIND_ALIASES",
	"find_latest_mes",
	"list_mes_files",
	"find_latest_mes_by_kind",
	"FEAExportSession",
	"FEAProcessResult",
	"prepare_fea_export_session",
	"orchestrate_fea_export",
	"process_fea_result_from_mes",
	# mes_backup
	"EXPORT_COLUMNS",
	"export_mes_to_txt",
	"find_all_backup_mes_files",
	"find_backup_mes_files",
	"find_backup_roots",
	"auto_resize_copper_after_geometry_update",
	# scaling
	"ScalingFactor",
	"MotorCADGeo",
	"ScaledMachineData",
	"scale_resistance_by_temp",
	"calc_current_density",
	"parse_mcad_colon_str",
	"def_scaling_factor",
	"get_mcad_machine_data",
	"get_mcad_building_data",
	"sl_scale_machine",
	"apply_scaled_data_to_mcad",
]

if _HAS_DOE_BATCH:
	__all__.extend(
		[
			"DOESolveResult",
			"DOEExportResult",
			"doe_solve_single",
			"doe_export_txt",
			"doe_export_txt_from_saved",
			"doe_export_h5_from_txt",
			"doe_export_h5",
			"doe_batch_run",
			"doe_h5_batch_from_txt",
			"doe_export_from_saved",
			"doe_scan_status",
			"doe_repair_missing_txt",
		]
	)
