% pyenv('Version', ... 
%             'C:\Users\KDH2018-PC\anaconda3\envs\py38_pcan151\python.exe', ... 
%             'ExecutionMode','InProcess') 

% pyenv('Version', ... 
%             'C:\Program Files\JMAG-Designer22.2\python3.8\python.exe', ... 
%             'ExecutionMode','InProcess') 
