# -*- coding: utf-8 -*-
"""d6_c67_stress.py -- D6: C67 회전자 원심 응력 추출 (rotor centrifugal stress).

이 파일은 **읽기 전용 참조 구현**이다.  moa 는 이 디렉터리를
`mlxperPJT/thermal/freeflow/scripts/` 로 복사(promote)한 뒤
`22_d6_c67_stress.py` 로 이름을 바꿔 커밋한다.
같은 디렉터리 안에서만 import 한다:  `import thesis_style as ts`.

계획서: `mlxperPJT/thermal/plans/PLAN_20260906_thesis_thermal.md` §1 D6.
산출물: `mlxperPJT/thermal/thesis_out/c67_stress.json`
        `mlxperPJT/thermal/thesis_out/c67_stress_vonmises.png`   (<= 300 KB)
        `mlxperPJT/thermal/thesis_out/c67_stress_ur.png`         (<= 300 KB)
        `mlxperPJT/thermal/thesis_out/c67_stress_vs_speed.png`   (덤, 3장 TODO(ii))

═══════════════════════════════════════════════════════════════════════════════
 ★ 시간 낭비 방지 경고 1 -- `251114_C67_test_Moa_Max3D.py` 는 구조해석이 아니다
═══════════════════════════════════════════════════════════════════════════════
레포 루트의 `251114_C67_test_Moa_Max3D.py` (22,191 행 / 1.05 MB) 는
**Motor-CAD 가 자동 생성한 AEDT / Maxwell 3D "Transient" 전자계 빌드 스크립트**다.

    1: # Ansys Electronics Desktop VBS file generated by Motor-CAD at 04/12/2025
    2: # 3D Electromagnetic model
   27: oProject.InsertDesign("Maxwell 3D", "...", "Transient", "")
  129: ["NAME:MachineRPM", ... "Value:=","5600RPM"]        <-- 전자계 운전점, 18000 rpm 아님
  127: ["NAME:IPeak",      ... "Value:=","630A"]

이 파일은 `.rst` 를 만들 수 없고 만들 의도도 없다.  구조해석 모델이 **아니다**.
이 파일에서 가져올 수 있는 것은 **형상/재료/축 규약의 정본**뿐이다:
  로터 OD 150 mm(r=75), 샤프트 70 mm(r=35), 공극 0.8 mm, 적층장 96 mm, 8극 48슬롯,
  L1 브리지/포스트 3.0/3.0 mm, L2 브리지/포스트 1.5/0.9 mm,
  슬리브 0 / 밴딩 0 / 축공 0 mm, 20PN1150F rho = 7650 kg/m^3,
  회전축 = **Z** ("Axis:=","Z" @22004,  CreateCircle "WhichAxis:=","Z" @689).
Maxwell 재료에는 E(Young) 도 nu(Poisson) 도 없다.  계획서의 E 192.5 GPa 는 여기서 온 값이
아니라 Motor-CAD `YoungsCoefficient_RotorLam` = 192500 MPa 다
(`mlxperPJT/KETI/RotorStress_e10.ipynb` cell 15, `pyMCAD2Maxwell.ipynb` cell 19).
=> **이 .py 를 다시 돌려 rst 를 얻으려는 시도에 1 시간도 쓰지 말 것.**

═══════════════════════════════════════════════════════════════════════════════
 ★ 시간 낭비 방지 경고 2 -- MAPDL /POST1 은 rst 하나만으로는 못 읽는다
═══════════════════════════════════════════════════════════════════════════════
`.rst` 에 절점/요소가 들어 있어도 대화형 MAPDL 의 `/POST1` 은 **DB(절점/요소)가 메모리에
올라와 있어야** `PRNSOL` / `post_processing.*` 가 동작한다.  Workbench `MECH` 폴더에는
기본적으로 `file.db` 가 저장되지 않는다(Analysis Settings "Save MAPDL db = No" 가 기본).
따라서:
  * `--rst` 하나만 있으면    -> 리더(DPF 또는 ansys.mapdl.reader)로만 읽을 수 있다.
  * `--mech-dir` 폴더 전체가 있으면 -> `ds.dat` / `file.db` / `.cdb` 가 있을 때만 MAPDL 재솔브
    (= `--sweep-method resolve`) 가 가능하다.
moa 로 복사할 때는 **`file.rst` 하나가 아니라 MECH 폴더 전체**를 가져오는 것이 안전하다.

═══════════════════════════════════════════════════════════════════════════════
 ★ 예비안 -- rst 도 wbpj 도 moa 에 도달하지 못하면 Motor-CAD 2D 경로가 있다
═══════════════════════════════════════════════════════════════════════════════
이 레포에 **이미 패키지·검증된** Motor-CAD 원심해석 경로가 있다:
    tools/motorCAD/pyMCAD/stress.py   (859 행: get_stress_data / StressRegions /
                                       plot_mesh_stress_fields / Neuber·Glinka 보정)
    mlxperPJT/KETI/RotorStress_e10.ipynb   (cell 8 에 C67 .mot 경로가 주석으로 남아 있음)
`.mot` 파일 하나만 있으면
    mc.set_variable("ShaftSpeed", 18000); mc.do_mechanical_calculation()
    regions = get_stress_data(mc)
로 끝나고, `MaxStress_RotorLam` / `MaxDisplacement_RotorLam` / **`SafetyFactor_RotorLam`**
(ActiveXParametersMotorCADv261.txt #5067 / #5083 / #5076) 를 스칼라로 바로 준다.
단점: 2D 평면 해석이라 WB 3D rst 와 수치가 정확히 같지 않다 -> `_soltype` 에 반드시 구분 기록.
**이 스크립트는 그 경로를 구현하지 않는다** (Motor-CAD 세션이 필요하고 D6 범위를 넘는다).
필요해지면 위 두 파일을 그대로 쓰면 된다.

═══════════════════════════════════════════════════════════════════════════════
 반경방향 변위의 정의 -- sqrt(ux^2+uy^2) 를 쓰지 말 것
═══════════════════════════════════════════════════════════════════════════════
회전축이 Z 이므로
    th  = atan2(y, x)
    u_r = ux*cos(th) + uy*sin(th)      <-- 부호가 살아 있는 정확한 반경변위
`sqrt(ux^2+uy^2)` 는 |u_r| 이 아니라 **면내 변위 크기**이고 u_theta != 0 이면 과대평가한다.
같은 함수가 레포에 이미 있다: `mlxperPJT/nvh/e10_paper_figs.py:58-60` (`radial_amp`).
MAPDL 경로에서는 `mapdl.rsys(1)` 후 `nodal_displacement("X")` 가 곧 u_r 이다.

═══════════════════════════════════════════════════════════════════════════════
 CLI
═══════════════════════════════════════════════════════════════════════════════
    python d6_c67_stress.py --dry-run
    python d6_c67_stress.py --rst  "C:/.../C67_stress_files/dp0/SYS-5/MECH/file.rst"
    python d6_c67_stress.py --mech-dir "C:/.../dp0/SYS-5/MECH" --sweep-method resolve
    python d6_c67_stress.py --rst ... --rpm 18000 --sweep 12000,15000,18000,21000

python 3.10 안전 (match 없음, `X | Y` 어노테이션 없음, 3.11+ stdlib 없음).
numpy 는 리더 경로에서만 필요하고 `--dry-run` 은 stdlib 만으로도 돈다.
"""

import argparse
import hashlib
import json
import math
import os
import subprocess
import sys
import time

# numpy 는 있으면 쓰고 없으면 (dry-run 한정) 순수 파이썬으로 돈다.
try:
    import numpy as _np
except Exception:                                    # pragma: no cover
    _np = None


# =========================================================================== #
#  0. 상수 -- 전부 출처가 있는 값.  근거 없는 숫자는 이 파일에 없다.            #
# =========================================================================== #

#: 회전축.  4중 확인 (Maxwell AssignBand "Axis:=","Z" / CreateCircle "WhichAxis:=","Z"
#: / KETI/Discovery.json Rotation.Direction=[0,0,1] / pyMCAD stress.py 가 Ux,Uy 만 export)
ROTATION_AXIS = "Z"

#: 형상 기본값 -- 251114_C67_test_Moa_Max3D.py L54-L120 (CLI 로 덮어쓸 수 있다)
R_SHAFT_MM_DEFAULT = 35.0      # DiaShaft 70 mm
R_ROTOR_MM_DEFAULT = 75.0      # RotorDia 150 mm
AIRGAP_MM_DEFAULT = 0.8        # Airgap 0.8 mm
STACK_MM_DEFAULT = 96.0        # Rotor_Lam_Length 96 mm

#: 재료 기본값
RHO_DEFAULT = 7650.0           # 20PN1150F mass_density, Max3D L237/L355 + Discovery.json
E_GPA_DEFAULT = 192.5          # Motor-CAD YoungsCoefficient_RotorLam = 192500 MPa
POISSON_DEFAULT = 0.3          # Motor-CAD PoissonsRatio_RotorLam
MU_DEFAULT = 0.2               # Motor-CAD AdhesionFactor_Magnets (#4988, 기본 0.2)
CONTACT_DEFAULT = "bonded"
ELEMENT_MM_DEFAULT = 0.3       # Motor-CAD MechanicalMeshLength_RotorLam (#4978)

#: 20PN1150F 항복강도는 **미상**이다.  Motor-CAD 기본값 305 MPa 는 플레이스홀더(#5007)이지
#: 이 강재의 실측값이 아니다.  --yield-MPa 로 명시하지 않으면 JSON 에 null 을 쓴다.
YIELD_MPA_DEFAULT = None

RPM_DEFAULT = 18000.0
SWEEP_DEFAULT = "12000,15000,18000,21000"

#: 해석해 sanity 게이트 (회전 원환, 평면응력).  18 krpm 기준값 -- 이 파일에서 계산해
#: 아래 상수와 대조한다(공식 오타 자체 검증).  단위 MPa / um.
ANALYTIC_REF_18K = {
    "rpm": 18000.0,
    "omega_rad_s": 1884.9555921538759,
    "sigma_theta_inner_MPa": 131.9632,
    "sigma_theta_outer_MPa": 54.2259,
    "u_r_outer_um": 21.1270,
}
ANALYTIC_REF_TOL_REL = 1e-4

#: FE 최대 von Mises 는 브리지/포스트 응력집중 때문에 보어 후프응력의 2~4 배가 정상.
SVM_BAND_X_HOOP = (2.0, 4.0)
#: FE 최대 반경변위 정상 범위 [um] @18 krpm (자석 질량 탑재 효과 포함).
UR_BAND_UM_18K = (20.0, 50.0)

#: 단위 자동판별 임계값
STRESS_PA_THRESHOLD = 1.0e6    # |sigma|max > 1e6 이면 Pa 로 본다 (MPa 면 수백)
LENGTH_M_THRESHOLD = 1.0       # |xyz|max < 1 이면 m 로 본다 (mm 면 수십)

SOURCES_NOTE = ("251114_C67_test_Moa_Max3D.py L54-L120 (geometry, rho); "
                "MotorCAD YoungsCoefficient_RotorLam/PoissonsRatio_RotorLam "
                "(E, nu); AdhesionFactor_Magnets #4988 (mu)")


# =========================================================================== #
#  1. 로깅 -- stdout + 파일 동시.  moa 는 이 스크립트를 무인으로 돌린다.        #
# =========================================================================== #

class Log(object):
    """stdout 과 로그 파일에 동시에 쓴다.  cp949 콘솔에서도 한글이 깨지지 않게 처리."""

    def __init__(self, path=None):
        self.path = path
        self.fh = None
        self.t0 = time.time()
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass
        if path:
            d = os.path.dirname(os.path.abspath(path))
            if d and not os.path.isdir(d):
                os.makedirs(d)
            self.fh = open(path, "a", encoding="utf-8")
            self.fh.write("\n" + "=" * 78 + "\n")
            self.fh.write("d6_c67_stress.py  %s\n"
                          % time.strftime("%Y-%m-%d %H:%M:%S"))
            self.fh.write("=" * 78 + "\n")
            self.fh.flush()

    def __call__(self, msg=""):
        line = "[%7.1fs] %s" % (time.time() - self.t0, msg) if msg else ""
        try:
            sys.stdout.write(line + "\n")
        except UnicodeEncodeError:                    # pragma: no cover
            sys.stdout.write(line.encode("ascii", "replace").decode("ascii") + "\n")
        try:
            sys.stdout.flush()
        except Exception:
            pass
        if self.fh:
            self.fh.write(line + "\n")
            self.fh.flush()

    def rule(self, title=""):
        self("-" * 74)
        if title:
            self(title)
            self("-" * 74)

    def close(self):
        if self.fh:
            self.fh.close()
            self.fh = None


# =========================================================================== #
#  2. 배열 헬퍼 -- numpy 가 있으면 numpy, 없으면 리스트로도 동작한다.           #
# =========================================================================== #

def _is_nan(v):
    try:
        return v != v
    except Exception:
        return True


def _nanargmax(a):
    """NaN 을 건너뛰는 argmax.  전부 NaN 이면 -1."""
    if _np is not None and isinstance(a, _np.ndarray):
        if not _np.any(_np.isfinite(a)):
            return -1
        return int(_np.nanargmax(a))
    best_i, best_v = -1, None
    for i, v in enumerate(a):
        if _is_nan(v):
            continue
        if best_v is None or v > best_v:
            best_i, best_v = i, v
    return best_i


def _nanmax(a):
    i = _nanargmax(a)
    return float("nan") if i < 0 else float(a[i])


def _nanmin(a):
    if _np is not None and isinstance(a, _np.ndarray):
        if not _np.any(_np.isfinite(a)):
            return float("nan")
        return float(_np.nanmin(a))
    best = None
    for v in a:
        if _is_nan(v):
            continue
        if best is None or v < best:
            best = v
    return float("nan") if best is None else float(best)


def _nanmean(a):
    if _np is not None and isinstance(a, _np.ndarray):
        if not _np.any(_np.isfinite(a)):
            return float("nan")
        return float(_np.nanmean(a))
    s, n = 0.0, 0
    for v in a:
        if _is_nan(v):
            continue
        s += float(v)
        n += 1
    return float("nan") if n == 0 else s / n


def _nanmaxabs(a):
    if _np is not None and isinstance(a, _np.ndarray):
        b = _np.abs(_np.asarray(a, dtype=float))
        if not _np.any(_np.isfinite(b)):
            return float("nan")
        return float(_np.nanmax(b))
    best = None
    for v in a:
        if _is_nan(v):
            continue
        v = abs(float(v))
        if best is None or v > best:
            best = v
    return float("nan") if best is None else best


def _percentile(a, q):
    """numpy 없으면 정렬 기반 근사.  컨투어 clim 용이라 정밀도 요구가 낮다."""
    if _np is not None and isinstance(a, _np.ndarray):
        b = a[_np.isfinite(a)]
        if b.size == 0:
            return float("nan")
        return float(_np.percentile(b, q))
    vals = sorted(float(v) for v in a if not _is_nan(v))
    if not vals:
        return float("nan")
    k = (len(vals) - 1) * q / 100.0
    lo, hi = int(math.floor(k)), int(math.ceil(k))
    if lo == hi:
        return vals[lo]
    return vals[lo] * (hi - k) + vals[hi] * (k - lo)


def _py(obj):
    """numpy 스칼라/배열을 json 이 먹을 수 있는 순수 파이썬으로 변환."""
    if obj is None or isinstance(obj, (bool, str)):
        return obj
    if isinstance(obj, dict):
        return dict((str(k), _py(v)) for k, v in obj.items())
    if isinstance(obj, (list, tuple)):
        return [_py(v) for v in obj]
    if isinstance(obj, float):
        return None if (obj != obj or obj in (float("inf"), float("-inf"))) else obj
    if isinstance(obj, int):
        return obj
    if _np is not None and isinstance(obj, _np.generic):
        return _py(obj.item())
    if _np is not None and isinstance(obj, _np.ndarray):
        return _py(obj.tolist())
    return obj


# =========================================================================== #
#  3. 회전 -- omega 변환과 omega^2 스케일링                                     #
# =========================================================================== #

def omega_rad_s(rpm):
    """rpm -> rad/s.   MAPDL `OMEGA,,,wz` 에 그대로 들어가는 값."""
    return float(rpm) * 2.0 * math.pi / 60.0


def omega2_scale(rpm, rpm_ref):
    """(n/n_ref)^2.

    선형탄성 + 순수 원심체적력 f = rho*omega^2*r + 동차 변위 BC 이면 지배방정식이
    omega^2 에 완전히 선형이므로  sigma(n) = sigma(n_ref)*(n/n_ref)^2  는
    **근사가 아니라 정확한 항등식**이다.  깨지는 조건은 4 가지뿐:
      (a) 소성/비선형 재료  (b) frictional 접촉의 개폐 변화
      (c) 압입/열하중 등 속도에 무관한 상수항  (d) NLGEOM/spin softening
    C67 은 슬리브 0 / 밴딩 0 / 축공 0 이라 (c) 는 없고, bonded 이면 (b) 도 없다.
    Neuber/Glinka 소성보정을 **적용한 뒤의** 값에는 절대 쓰면 안 된다.
    """
    return (float(rpm) / float(rpm_ref)) ** 2


# =========================================================================== #
#  4. 해석해 게이트 -- 회전 원환(평면응력).  단위 오독을 즉시 잡는다.           #
# =========================================================================== #

def annulus_plane_stress(rpm, a_m, b_m, nu, rho, E_Pa):
    """자유-자유 회전 원환(내경 a, 외경 b, 평면응력)의 닫힌해.

        sigma_r(r)     = (3+nu)/8 * rho*w^2 * (a^2 + b^2 - a^2 b^2/r^2 - r^2)
        sigma_theta(r) = (3+nu)/8 * rho*w^2 * (a^2 + b^2 + a^2 b^2/r^2
                                               - (1+3nu)/(3+nu) * r^2)
        u_r(r)         = r*(sigma_theta - nu*sigma_r)/E

    반환 dict 의 응력 단위는 MPa, 변위 단위는 um / mm.
    """
    w = omega_rad_s(rpm)
    c = (3.0 + nu) / 8.0 * rho * w * w
    k = (1.0 + 3.0 * nu) / (3.0 + nu)
    a2, b2 = a_m * a_m, b_m * b_m

    def s_r(r):
        return c * (a2 + b2 - a2 * b2 / (r * r) - r * r)

    def s_t(r):
        return c * (a2 + b2 + a2 * b2 / (r * r) - k * r * r)

    def u_r(r):
        return r * (s_t(r) - nu * s_r(r)) / E_Pa

    return {
        "rpm": float(rpm),
        "omega_rad_s": w,
        "a_m": float(a_m), "b_m": float(b_m),
        "nu": float(nu), "rho_kg_m3": float(rho), "E_Pa": float(E_Pa),
        "sigma_theta_inner_MPa": s_t(a_m) / 1e6,
        "sigma_theta_outer_MPa": s_t(b_m) / 1e6,
        "sigma_r_inner_MPa": s_r(a_m) / 1e6,
        "sigma_r_outer_MPa": s_r(b_m) / 1e6,
        "u_r_outer_um": u_r(b_m) * 1e6,
        "u_r_outer_mm": u_r(b_m) * 1e3,
        "_field_fn": {"s_r": s_r, "s_t": s_t, "u_r": u_r},
        "_note": ("free-free rotating annulus, plane stress, homogeneous isotropic; "
                  "no bridges/posts/magnets -> FE max von Mises is expected to be "
                  "2-4x the bore hoop stress"),
    }


def verify_analytic_formula(log):
    """공식 자체가 맞는지(오타가 없는지) 18 krpm 고정 기준값과 대조한다.

    Ansys 가 없어도 무조건 실행되는 self-check.  실패하면 즉시 죽는다 --
    이 공식이 틀리면 아래의 모든 sanity 판정이 거짓말이 된다.
    """
    ref = ANALYTIC_REF_18K
    got = annulus_plane_stress(ref["rpm"], 0.035, 0.075, 0.3, 7650.0, 192.5e9)
    checks = []
    for key in ("omega_rad_s", "sigma_theta_inner_MPa",
                "sigma_theta_outer_MPa", "u_r_outer_um"):
        want, have = float(ref[key]), float(got[key])
        rel = abs(have - want) / max(abs(want), 1e-30)
        ok = rel <= ANALYTIC_REF_TOL_REL
        checks.append({"key": key, "expected": want, "got": have,
                       "rel_err": rel, "ok": ok})
        log("    %-24s expected %14.6f   got %14.6f   rel %.2e   %s"
            % (key, want, have, rel, "OK" if ok else "FAIL"))
    bad = [c for c in checks if not c["ok"]]
    if bad:
        raise AssertionError("analytic annulus formula self-check FAILED: %s"
                             % [c["key"] for c in bad])
    return checks


def sanity_gate(max_svm_MPa, max_ur_mm, rpm, ana, log):
    """단위(Pa vs MPa, m vs mm) 오독과 잘못된 set 읽기를 즉시 잡는 게이트.

    * von Mises: 보어 후프응력의 2~4 배가 정상 (브리지/포스트 응력집중).
    * 반경변위 : 18 krpm 기준 20~50 um, 다른 속도에서는 (n/18000)^2 로 스케일.
    PASS / WARN 을 찍고 dict 를 돌려준다.  **WARN 이어도 죽이지 않는다** --
    C67 이 정말로 그 범위 밖일 수도 있고, 판단은 사람이 한다.
    """
    hoop = float(ana["sigma_theta_inner_MPa"])
    svm_lo, svm_hi = SVM_BAND_X_HOOP[0] * hoop, SVM_BAND_X_HOOP[1] * hoop
    sc = omega2_scale(rpm, 18000.0)
    ur_lo = UR_BAND_UM_18K[0] * sc / 1000.0        # um -> mm
    ur_hi = UR_BAND_UM_18K[1] * sc / 1000.0

    warns = []
    svm_ok = (not _is_nan(max_svm_MPa)) and (svm_lo <= max_svm_MPa <= svm_hi)
    ur_ok = (not _is_nan(max_ur_mm)) and (ur_lo <= max_ur_mm <= ur_hi)
    if not svm_ok:
        warns.append("max von Mises %.4g MPa outside [%.4g, %.4g] MPa "
                     "(= %.1f-%.1f x bore hoop %.4g MPa) -- check Pa vs MPa, "
                     "the result set, or accept it as a real design finding"
                     % (max_svm_MPa, svm_lo, svm_hi, SVM_BAND_X_HOOP[0],
                        SVM_BAND_X_HOOP[1], hoop))
    if not ur_ok:
        warns.append("max radial displacement %.4g mm outside [%.4g, %.4g] mm "
                     "-- check m vs mm" % (max_ur_mm, ur_lo, ur_hi))

    log("  analytic annulus @%.0f rpm : hoop(bore) %.2f MPa, hoop(rim) %.2f MPa, "
        "u_r(rim) %.2f um" % (rpm, hoop, ana["sigma_theta_outer_MPa"],
                              ana["u_r_outer_um"]))
    log("  expected FE band          : von Mises [%.1f, %.1f] MPa, "
        "delta_r [%.4f, %.4f] mm" % (svm_lo, svm_hi, ur_lo, ur_hi))
    log("  measured                  : von Mises %.4g MPa, delta_r %.5g mm"
        % (max_svm_MPa, max_ur_mm))
    log("  SANITY GATE: %s" % ("PASS" if (svm_ok and ur_ok) else "WARN"))
    for w in warns:
        log("    WARN: " + w)

    return {
        "passed": bool(svm_ok and ur_ok),
        "von_mises_ok": bool(svm_ok),
        "radial_disp_ok": bool(ur_ok),
        "expected_svm_band_MPa": [svm_lo, svm_hi],
        "expected_ur_band_mm": [ur_lo, ur_hi],
        "band_definition": ("von Mises in [%.1f, %.1f] x analytic bore hoop; "
                            "delta_r in [%.0f, %.0f] um scaled by (n/18000)^2"
                            % (SVM_BAND_X_HOOP[0], SVM_BAND_X_HOOP[1],
                               UR_BAND_UM_18K[0], UR_BAND_UM_18K[1])),
        "measured_max_von_mises_MPa": _py(max_svm_MPa),
        "measured_max_radial_disp_mm": _py(max_ur_mm),
        "warnings": warns,
    }


# =========================================================================== #
#  5. 리더 프로브 -- dpf -> ansys.mapdl.reader -> ansys.mapdl.core             #
# =========================================================================== #

def probe_readers(log):
    """무엇을 실제로 쓸 수 있는지 조사해서 기록한다.

    `ansys.dpf.core` 는 이 레포 전체(py/ipynb/md/txt)에 사용례가 **0 건**이고
    moa 의 venv 인벤토리에도 없다.  따라서 **절대 요구사항으로 두지 않는다** --
    여기서 try/except 로 존재만 확인하고, 없으면 조용히 다음 후보로 간다.
    `ansys.mapdl.reader` 는 `mlxperPJT/thermal/thermal_viz.py:60` 이 이미 쓰고 있다.
    """
    found = {}
    for name, mod in (("dpf", "ansys.dpf.core"),
                      ("mapdl_reader", "ansys.mapdl.reader"),
                      ("mapdl", "ansys.mapdl.core"),
                      ("pyvista", "pyvista"),
                      ("numpy", "numpy"),
                      ("matplotlib", "matplotlib")):
        try:
            m = __import__(mod, fromlist=["__version__"])
            ver = getattr(m, "__version__", "?")
            found[name] = str(ver)
            log("  probe %-14s -> AVAILABLE (%s)" % (mod, ver))
        except Exception as exc:
            found[name] = None
            log("  probe %-14s -> missing (%s: %s)"
                % (mod, type(exc).__name__, str(exc)[:90]))
    if found.get("dpf") is None:
        log("  note: ansys.dpf.core is absent -- expected; it has ZERO uses in this "
            "repo and is not a requirement.  If you want it: "
            "<venv>\\Scripts\\python.exe -m pip install ansys-dpf-core")
    return found


def pick_reader(requested, avail, log):
    """실제로 시도할 리더 후보를 **순서대로** 돌려준다.

    `--reader` 를 명시하면 그것 하나만.  `auto` 면 dpf -> mapdl_reader 순으로
    후보를 만든다 (import 가 되는 것만).  DPF 의 세부 API(`stress_von_mises` 노출,
    `von_mises_eqv_fc` 시그니처)는 이 레포에서 한 번도 검증된 적이 없으므로
    **첫 후보가 예외를 던지면 다음 후보로 넘어간다** -- 그래서 리스트다.
    `mapdl`(ansys.mapdl.core)은 rst 단독으로는 못 읽으므로 이 목록에 넣지 않는다.
    """
    order = ("dpf", "mapdl_reader")
    if requested == "mapdl":
        raise RuntimeError(
            "--reader mapdl cannot read a lone .rst: MAPDL /POST1 needs the node/"
            "element database (file.db / .cdb / ds.dat), which a Workbench MECH "
            "folder does not save by default.  Drop --rst and pass --mech-dir so the "
            "model is re-solved, or use --reader mapdl_reader / dpf.")
    if requested and requested != "auto":
        if avail.get(requested) is None:
            raise RuntimeError("--reader %s requested but the module is not "
                               "importable (probe said missing)" % requested)
        return [requested]
    cands = [n for n in order if avail.get(n)]
    if not cands:
        raise RuntimeError(
            "no result reader available.  Install one into the moa venv:\n"
            "  <venv>\\Scripts\\python.exe -m pip install ansys-mapdl-reader\n"
            "  (or ansys-dpf-core).  ansys-mapdl-core alone cannot read a lone .rst; "
            "for that route pass --mech-dir with ds.dat / file.db / a .cdb.")
    log("  reader candidates (in order): %s" % ", ".join(cands))
    return cands


# =========================================================================== #
#  6. 단위 판별 + 필드 파생                                                     #
# =========================================================================== #

def infer_stress_scale(raw_max_abs, log):
    """rst 는 solve 단위계로 저장된다.  Pa 이면 1e-6, MPa 이면 1.0 을 돌려준다."""
    if _is_nan(raw_max_abs) or raw_max_abs <= 0.0:
        log("  stress unit: undetermined (max|S| = %r) -> assuming MPa" % raw_max_abs)
        return 1.0, "undetermined->MPa"
    if raw_max_abs > STRESS_PA_THRESHOLD:
        log("  stress unit: max|S| = %.4g > %.0e -> native Pa, scaling by 1e-6"
            % (raw_max_abs, STRESS_PA_THRESHOLD))
        return 1.0e-6, "Pa"
    log("  stress unit: max|S| = %.4g <= %.0e -> native MPa, no scaling"
        % (raw_max_abs, STRESS_PA_THRESHOLD))
    return 1.0, "MPa"


def infer_length_scale(raw_max_abs, log):
    """좌표계 단위.  로터 OD 는 0.075 m 또는 75 mm 여야 한다."""
    if _is_nan(raw_max_abs) or raw_max_abs <= 0.0:
        log("  length unit: undetermined -> assuming mm")
        return 1.0, "undetermined->mm"
    if raw_max_abs < LENGTH_M_THRESHOLD:
        log("  length unit: max|xyz| = %.4g < %.1f -> native m, scaling by 1e3"
            % (raw_max_abs, LENGTH_M_THRESHOLD))
        return 1.0e3, "m"
    log("  length unit: max|xyz| = %.4g >= %.1f -> native mm, no scaling"
        % (raw_max_abs, LENGTH_M_THRESHOLD))
    return 1.0, "mm"


def derive_fields(fields, log):
    """xyz_mm 과 u_mm 에서 r, theta, u_r, |u| 를 만든다.

    u_r = ux*cos(th) + uy*sin(th),  th = atan2(y, x)   (회전축 = Z)
    `mlxperPJT/nvh/e10_paper_figs.py:58-60` (radial_amp) 와 동일한 정의.
    """
    xyz = fields["xyz_mm"]
    u = fields.get("u_mm")
    if _np is not None and isinstance(xyz, _np.ndarray):
        x, y = xyz[:, 0], xyz[:, 1]
        th = _np.arctan2(y, x)
        fields["r_mm"] = _np.hypot(x, y)
        fields["theta_deg"] = _np.degrees(th)
        if u is not None:
            fields["u_r_mm"] = u[:, 0] * _np.cos(th) + u[:, 1] * _np.sin(th)
            fields["u_mag_mm"] = _np.sqrt((u[:, :3] ** 2).sum(axis=1))
    else:
        n = len(xyz)
        r = [0.0] * n
        td = [0.0] * n
        ur = [0.0] * n if u is not None else None
        um = [0.0] * n if u is not None else None
        for i in range(n):
            xi, yi = float(xyz[i][0]), float(xyz[i][1])
            th = math.atan2(yi, xi)
            r[i] = math.hypot(xi, yi)
            td[i] = math.degrees(th)
            if u is not None:
                ux, uy, uz = float(u[i][0]), float(u[i][1]), float(u[i][2])
                ur[i] = ux * math.cos(th) + uy * math.sin(th)
                um[i] = math.sqrt(ux * ux + uy * uy + uz * uz)
        fields["r_mm"] = r
        fields["theta_deg"] = td
        if u is not None:
            fields["u_r_mm"] = ur
            fields["u_mag_mm"] = um
    log("  derived r/theta/u_r for %d nodes (u_r = ux*cos(th)+uy*sin(th), axis=%s)"
        % (len(fields["xyz_mm"]), ROTATION_AXIS))
    return fields


def _align_to(target_ids, src_ids, src_vals, ncol, log=None, label=""):
    """src_vals 를 target_ids 순서로 재배열한다 (numpy 필요).  없는 절점은 NaN.

    **절점 순서를 절대 가정하지 않는다.**  DPF 의 `field.scoping.ids` 는 메시의
    `nodes.scoping.ids` 와 다를 수 있고, reader 의 `principal_nodal_stress` 도
    결과가 있는 절점만 돌려준다.  적중률을 로그에 남겨서 "조용히 절반이 NaN"
    같은 사고를 눈에 보이게 한다.
    """
    if _np is None:
        raise RuntimeError("_align_to needs numpy")
    t = _np.asarray(target_ids, dtype=_np.int64)
    s = _np.asarray(src_ids, dtype=_np.int64)
    v = _np.asarray(src_vals, dtype=float)
    if v.ndim == 1:
        v = v.reshape(-1, 1)
    if v.shape[1] < ncol:
        raise RuntimeError("%s: expected >=%d component(s), got %d"
                           % (label or "field", ncol, v.shape[1]))
    v = v[:, :ncol]
    if s.size == t.size and bool(_np.array_equal(s, t)):
        out = v
        hit = int(t.size)
    else:
        lut = {}
        for i in range(s.size):
            lut[int(s[i])] = i
        out = _np.full((t.size, ncol), _np.nan, dtype=float)
        hit = 0
        for i in range(t.size):
            j = lut.get(int(t[i]))
            if j is not None:
                out[i, :] = v[j, :]
                hit += 1
    if log is not None:
        log("  align %-14s: %d/%d target nodes matched (%.1f %%)"
            % (label or "field", hit, t.size,
               100.0 * hit / max(int(t.size), 1)))
        if hit == 0:
            log("  WARN: zero overlap between the field scoping and the mesh node "
                "ids -- the result will be all-NaN")
    return out if ncol > 1 else out[:, 0]


# =========================================================================== #
#  7. 리더 구현                                                                 #
# =========================================================================== #

def read_rst_dpf(rst, log):
    """ansys.dpf.core.  이 레포에 사용례가 없으므로 전 구간 방어적으로 감싼다."""
    from ansys.dpf import core as dpf                       # noqa: F401

    log("  DPF: opening model")
    model = dpf.Model(rst)
    mesh = model.metadata.meshed_region
    n_sets = 1
    try:
        n_sets = int(model.metadata.time_freq_support.n_sets)
    except Exception as exc:
        log("  DPF: n_sets unavailable (%s) -> assuming 1" % exc)

    node_ids = _np.asarray(mesh.nodes.scoping.ids, dtype=_np.int64)
    coords = _np.asarray(mesh.nodes.coordinates_field.data, dtype=float)
    coords = coords.reshape(node_ids.size, 3)

    # --- von Mises (nodal, averaged) -------------------------------------
    sop = model.results.stress()
    sop.inputs.time_scoping.connect([1])
    sop.inputs.requested_location.connect(dpf.locations.nodal)
    vm = dpf.operators.invariant.von_mises_eqv_fc(
        fields_container=sop.outputs.fields_container)
    f = vm.outputs.fields_container()[0]
    svm_raw = _align_to(node_ids, _np.asarray(f.scoping.ids), _np.asarray(f.data),
                        1, log=log, label="von Mises")

    # --- displacement -----------------------------------------------------
    dop = model.results.displacement()
    dop.inputs.time_scoping.connect([1])
    df = dop.outputs.fields_container()[0]
    u_raw = _align_to(node_ids, _np.asarray(df.scoping.ids),
                      _np.asarray(df.data).reshape(-1, 3), 3,
                      log=log, label="displacement")

    grid = None
    try:
        grid = mesh.grid
    except Exception as exc:
        log("  DPF: mesh.grid unavailable (%s) -> point cloud fallback" % exc)

    return {"nnum": node_ids, "xyz_raw": coords, "svm_raw": svm_raw,
            "u_raw": u_raw, "grid": grid, "n_sets": n_sets,
            "reader": "ansys.dpf.core",
            "averaging": "nodal (elemental-nodal averaged, DPF default)"}


def read_rst_mapdl_reader(rst, log):
    """ansys.mapdl.reader.read_binary -- 이 레포가 이미 쓰는 경로.

    thermal_viz.py:60 이 `from ansys.mapdl import reader as rd` 로 import 한다.
        nnum, pstr = res.principal_nodal_stress(0)
        von Mises  = pstr[:, 4]     (S1,S2,S3,SINT,SEQV 순서의 5번째)
        res.nodal_solution(0) -> (nnum, U)  변위
    principal_nodal_stress 는 결과가 없는 절점에 NaN 을 넣는다 -> nan-aware 통계 필수.
    """
    from ansys.mapdl import reader as rd

    log("  mapdl.reader: read_binary(%s)" % rst)
    res = rd.read_binary(rst)

    n_sets = 1
    try:
        n_sets = int(res.nsets)
    except Exception:
        try:
            n_sets = len(res.time_values)
        except Exception:
            pass
    log("  mapdl.reader: nsets = %d (using set 0)" % n_sets)

    mesh_nnum = _np.asarray(res.mesh.nnum, dtype=_np.int64)
    coords = _np.asarray(res.mesh.nodes, dtype=float)[:, :3]

    snum, pstr = res.principal_nodal_stress(0)
    pstr = _np.asarray(pstr, dtype=float)
    if pstr.ndim != 2 or pstr.shape[1] < 5:
        raise RuntimeError("principal_nodal_stress returned shape %r; expected "
                           "(n, >=5) = (S1, S2, S3, SINT, SEQV)" % (pstr.shape,))
    svm_raw = _align_to(mesh_nnum, _np.asarray(snum), pstr[:, 4], 1,
                        log=log, label="SEQV")

    dnum, U = res.nodal_solution(0)
    U = _np.asarray(U, dtype=float)
    if U.ndim != 2 or U.shape[1] < 2:
        raise RuntimeError("nodal_solution returned shape %r; expected (n, >=2) "
                           "ux/uy[/uz] -- is this a structural result file?"
                           % (U.shape,))
    # 2 DOF/node = 2D plane model (Motor-CAD mechanical is 2D).  The rotation axis is Z,
    # so u_r = ux*cos(th) + uy*sin(th) is unchanged; there simply is no uz.  Pad it with
    # zeros so everything downstream keeps working on an (n, 3) array.
    if U.shape[1] == 2:
        model_dim = "2D"
        log("  mapdl.reader: 2 DOF/node -> 2D plane model; uz padded with zeros "
            "(u_r = ux*cos(th) + uy*sin(th) is unaffected)")
        U = _np.column_stack([U[:, 0], U[:, 1], _np.zeros(len(U), dtype=float)])
    else:
        model_dim = "3D"
    u_raw = _align_to(mesh_nnum, _np.asarray(dnum), U[:, :3], 3,
                      log=log, label="displacement")

    grid = None
    try:
        grid = res.grid
    except Exception as exc:
        log("  mapdl.reader: res.grid unavailable (%s) -> point cloud fallback" % exc)

    return {"nnum": mesh_nnum, "xyz_raw": coords, "svm_raw": svm_raw,
            "u_raw": u_raw, "grid": grid, "n_sets": n_sets,
            "model_dim": model_dim,
            "reader": "ansys.mapdl.reader.read_binary",
            "averaging": "nodal (principal_nodal_stress column 4 = SEQV)"}


def _mapdl_load_db(mapdl, mech_dir, log):
    """MECH 폴더에서 DB 를 올린다.  .db -> .cdb -> ds.dat 순.

    Workbench MECH 폴더에는 보통 file.db 가 **없다**.  ds.dat 는 `/EXIT` 로 끝나므로
    그대로 input 하면 MAPDL 이 죽는다 -> 꼬리를 잘라 낸 사본을 만들어 넣는다.
    """
    from ansys.mapdl.core.errors import MapdlRuntimeError

    cands_db = [os.path.join(mech_dir, n) for n in ("file.db", "ds.db")]
    cands_cdb = [os.path.join(mech_dir, n) for n in ("file.cdb", "ds.cdb")]
    ds_dat = os.path.join(mech_dir, "ds.dat")

    for p in cands_db:
        if os.path.isfile(p):
            log("  MAPDL: resume(%s)" % p)
            try:
                mapdl.resume(p)
                return {"kind": "db", "path": p}
            except MapdlRuntimeError as exc:
                log("  MAPDL: resume failed (%s)" % str(exc)[:200])
    for p in cands_cdb:
        if os.path.isfile(p):
            stem = os.path.splitext(p)[0]
            log("  MAPDL: cdread('DB', %s, 'cdb')" % stem)
            try:
                mapdl.prep7()
                mapdl.cdread("DB", stem, "cdb")
                mapdl.finish()
                return {"kind": "cdb", "path": p}
            except MapdlRuntimeError as exc:
                log("  MAPDL: cdread failed (%s)" % str(exc)[:200])
    if os.path.isfile(ds_dat):
        trimmed = os.path.join(mapdl.directory, "ds_trimmed.dat")
        n_in, n_out = 0, 0
        with open(ds_dat, "r", encoding="utf-8", errors="replace") as fin:
            lines = fin.readlines()
        n_in = len(lines)
        keep = []
        for ln in lines:
            s = ln.strip().upper()
            if s.startswith("/EXIT") or s.startswith("/EOF"):
                break
            keep.append(ln)
        n_out = len(keep)
        with open(trimmed, "w", encoding="utf-8") as fo:
            fo.writelines(keep)
        log("  MAPDL: input(ds.dat) with the /EXIT tail trimmed (%d -> %d lines)"
            % (n_in, n_out))
        try:
            mapdl.input(trimmed)
            return {"kind": "ds.dat", "path": ds_dat,
                    "note": "tail trimmed at /EXIT; %d of %d lines used"
                            % (n_out, n_in)}
        except MapdlRuntimeError as exc:
            log("  MAPDL: input(ds.dat) failed (%s)" % str(exc)[:200])

    raise RuntimeError(
        "no MAPDL-loadable database in %s.  MAPDL /POST1 cannot read a lone .rst -- "
        "it needs file.db, a .cdb, or ds.dat.  Copy the WHOLE MECH folder, or use "
        "the reader route (--rst) instead." % mech_dir)


def _mapdl_extract(mapdl, log):
    """현재 /POST1 set 에서 SEQV 와 반경변위를 뽑는다."""
    seqv = _np.asarray(mapdl.post_processing.nodal_eqv_stress(), dtype=float)
    nnum = _np.asarray(mapdl.mesh.nnum, dtype=_np.int64)
    coords = _np.asarray(mapdl.mesh.nodes, dtype=float)[:, :3]
    # RSYS,1 = 전역 원통좌표 (축 = Z) -> UX 가 곧 u_r, UY 가 u_theta.
    mapdl.rsys(1)
    ur = _np.asarray(mapdl.post_processing.nodal_displacement("X"), dtype=float)
    ut = _np.asarray(mapdl.post_processing.nodal_displacement("Y"), dtype=float)
    uz = _np.asarray(mapdl.post_processing.nodal_displacement("Z"), dtype=float)
    mapdl.rsys(0)
    ux = _np.asarray(mapdl.post_processing.nodal_displacement("X"), dtype=float)
    uy = _np.asarray(mapdl.post_processing.nodal_displacement("Y"), dtype=float)
    U = _np.column_stack([ux, uy, uz])
    log("  MAPDL: extracted %d nodes (SEQV + RSYS,1 u_r)" % nnum.size)
    return {"nnum": nnum, "xyz_raw": coords, "svm_raw": seqv, "u_raw": U,
            "u_r_native": ur, "u_t_native": ut, "grid": None}


def solve_rst_mapdl(mech_dir, rpm_list, log, nproc=4, memory=None, run_dir=None):
    """MECH 폴더의 DB 를 올려 각 rpm 에서 원심하중 static 을 재솔브한다.

    원심하중은 `OMEGA, , , wz` (rad/s).  회전기준계용 `CGOMGA` 도, 컴포넌트용
    `CMOMEGA` 도 아니다.  회전중심은 원점(Discovery.json Rotation.Center=[0,0,0]).
    `mapdl.allsel("ALL")` 를 SOLVE 직전마다 반드시 부른다 -- SOLVE 는 현재 선택된
    요소만 푼다.  `mapdl.ignore_errors` 는 쓰지 않는다: MapdlRuntimeError 를 잡는다.
    """
    from ansys.mapdl.core import launch_mapdl
    from ansys.mapdl.core.errors import MapdlRuntimeError

    wd = run_dir or os.path.join(os.path.abspath(mech_dir), "_d6_mapdl_run")
    if not os.path.isdir(wd):
        os.makedirs(wd)
    log("  MAPDL: launching (run_location=%s, nproc=%d)" % (wd, nproc))
    kw = dict(run_location=wd, override=True, nproc=int(nproc),
              additional_switches="-smp")
    if memory:
        kw["memory"] = int(memory)
    mapdl = launch_mapdl(**kw)
    out = {}
    try:
        mapdl.clear()
        db = _mapdl_load_db(mapdl, mech_dir, log)
        log("  MAPDL: database loaded from %s (%s)" % (db["path"], db["kind"]))
        for rpm in rpm_list:
            w = omega_rad_s(rpm)
            log("  MAPDL: solving %.0f rpm  (OMEGA,,,%.10f rad/s)" % (rpm, w))
            try:
                mapdl.finish()
                mapdl.slashsolu()
                mapdl.antype("STATIC")
                mapdl.omega("", "", w)
                mapdl.allsel("ALL")          # SOLVE 는 선택된 것만 푼다 -- 필수
                mapdl.solve()
                mapdl.finish()
                mapdl.post1()
                mapdl.set(1, 1)
                out[float(rpm)] = _mapdl_extract(mapdl, log)
                out[float(rpm)]["omega_rad_s"] = w
                out[float(rpm)]["db"] = db
            except MapdlRuntimeError as exc:
                raise RuntimeError("MAPDL solve failed at %.0f rpm: %s"
                                   % (rpm, str(exc)[:400]))
    finally:
        try:
            mapdl.exit()
        except Exception:
            pass
    return out


# =========================================================================== #
#  8. 합성 필드 (--dry-run) -- Ansys 없이 파이프라인 전체를 돌린다.             #
# =========================================================================== #

def synthetic_fields(args, log, kt=None):
    """해석해 회전 원환에서 합성 절점장을 만든다.

    닫힌해의 sigma_r / sigma_theta 로 평면응력 von Mises 를 만들고, 보어 근처
    한 줄에 브리지 응력집중 계수 kt 를 곱해 FE 다운 최대값을 만든다.
    합성이라도 **파이프라인(단위 판별 -> 파생 -> 최대값 -> 게이트 -> 스윕 -> JSON ->
    그림)은 실제 경로와 완전히 동일한 코드**를 지난다.
    """
    kt = float(args.dry_run_kt if kt is None else kt)
    a = args.shaft_r_mm / 1000.0
    b = args.rotor_r_mm / 1000.0
    ana = annulus_plane_stress(args.rpm, a, b, args.poisson, args.rho,
                               args.E_GPa * 1e9)
    fn = ana["_field_fn"]

    n_r, n_t, n_z = int(args.dry_run_nr), int(args.dry_run_nt), int(args.dry_run_nz)
    zs = [(-args.stack_mm / 2.0 + args.stack_mm * k / max(n_z - 1, 1))
          for k in range(n_z)]

    nnum, xyz, svm, u = [], [], [], []
    nid = 0
    for k in range(n_z):
        for i in range(n_r):
            r = a + (b - a) * i / float(n_r - 1)
            sr, st = fn["s_r"](r), fn["s_t"](r)
            vm = math.sqrt(st * st - st * sr + sr * sr) / 1e6      # MPa
            urad = fn["u_r"](r) * 1000.0                            # mm
            for j in range(n_t):
                th = 2.0 * math.pi * j / float(n_t)
                nid += 1
                # 브리지 모사: 8 극이므로 45 deg 간격의 좁은 섹터 x 보어 근처에서
                # 응력집중 kt 를 준다.  (합성이라는 사실은 JSON 에 명시된다.)
                pol = abs(math.cos(4.0 * th))
                conc = 1.0 + (kt - 1.0) * (pol ** 24) * (1.0 - (r - a) / (b - a)) ** 2
                nnum.append(nid)
                xyz.append([r * math.cos(th) * 1000.0,
                            r * math.sin(th) * 1000.0, zs[k]])
                svm.append(vm * conc)
                u.append([urad * math.cos(th), urad * math.sin(th), 0.0])

    if _np is not None:
        nnum = _np.asarray(nnum, dtype=_np.int64)
        xyz = _np.asarray(xyz, dtype=float)
        svm = _np.asarray(svm, dtype=float)
        u = _np.asarray(u, dtype=float)
    log("  synthetic field: %d nodes (n_r=%d, n_theta=%d, n_z=%d), Kt=%.2f"
        % (len(nnum), n_r, n_t, n_z, kt))
    return {"nnum": nnum, "xyz_raw": xyz, "svm_raw": svm, "u_raw": u,
            "grid": None, "n_sets": 1,
            "reader": "synthetic (dry-run, analytic rotating annulus x Kt)",
            "averaging": "n/a (synthetic)",
            "_kt": kt}


# =========================================================================== #
#  9. 최대값 / 영역 통계 추출                                                   #
# =========================================================================== #

def _loc(fields, i):
    xyz = fields["xyz_mm"]
    return {"x": float(xyz[i][0]), "y": float(xyz[i][1]), "z": float(xyz[i][2]),
            "r": float(fields["r_mm"][i]), "theta_deg": float(fields["theta_deg"][i])}


def _mask_stats(fields, lo_mm, hi_mm):
    """반경 밴드 [lo, hi] mm 안의 통계."""
    r = fields["r_mm"]
    svm = fields["svm_MPa"]
    ur = fields.get("u_r_mm")
    if _np is not None and isinstance(r, _np.ndarray):
        m = (r >= lo_mm) & (r <= hi_mm)
        n = int(m.sum())
        if n == 0:
            return {"n_nodes": 0, "max_svm_MPa": None, "mean_svm_MPa": None,
                    "max_ur_mm": None, "r_mm_range": [lo_mm, hi_mm]}
        s = svm[m]
        out = {"n_nodes": n, "max_svm_MPa": _nanmax(s), "mean_svm_MPa": _nanmean(s),
               "r_mm_range": [lo_mm, hi_mm]}
        out["max_ur_mm"] = _nanmax(ur[m]) if ur is not None else None
        return out
    sel_s, sel_u, n = [], [], 0
    for i in range(len(r)):
        if lo_mm <= r[i] <= hi_mm:
            n += 1
            sel_s.append(svm[i])
            if ur is not None:
                sel_u.append(ur[i])
    if n == 0:
        return {"n_nodes": 0, "max_svm_MPa": None, "mean_svm_MPa": None,
                "max_ur_mm": None, "r_mm_range": [lo_mm, hi_mm]}
    return {"n_nodes": n, "max_svm_MPa": _nanmax(sel_s),
            "mean_svm_MPa": _nanmean(sel_s),
            "max_ur_mm": (_nanmax(sel_u) if sel_u else None),
            "r_mm_range": [lo_mm, hi_mm]}


def extract_maxima(fields, args, log):
    """최대 von Mises / 최대 반경변위와 그 절점번호·좌표(mm)를 뽑는다."""
    svm = fields["svm_MPa"]
    ur = fields["u_r_mm"]
    umag = fields["u_mag_mm"]
    nnum = fields["nnum"]

    i_s = _nanargmax(svm)
    i_u = _nanargmax(ur)
    i_m = _nanargmax(umag)
    if i_s < 0 or i_u < 0:
        raise RuntimeError("all-NaN stress or displacement field -- wrong result "
                           "set, or the reader returned nothing")

    res = {
        "rpm": float(args.rpm),
        "omega_rad_s": omega_rad_s(args.rpm),
        "max_von_mises_MPa": float(svm[i_s]),
        "max_von_mises_node": int(nnum[i_s]),
        "max_von_mises_loc_mm": _loc(fields, i_s),
        "max_radial_disp_mm": float(ur[i_u]),
        "max_radial_disp_node": int(nnum[i_u]),
        "max_radial_disp_loc_mm": _loc(fields, i_u),
        "min_radial_disp_mm": _nanmin(ur),
        "max_total_disp_mm": float(umag[i_m]),
        "max_total_disp_node": int(nnum[i_m]),
        "mean_von_mises_MPa": _nanmean(svm),
        "delta_r_definition": ("u_r = ux*cos(theta) + uy*sin(theta), "
                               "theta = atan2(y, x), rotation axis = Z "
                               "(signed projection, NOT sqrt(ux^2+uy^2))"),
        "n_nodes": int(len(nnum)),
    }
    rr = args.rotor_r_mm
    res["per_region"] = {
        "bore": _mask_stats(fields, 0.0, args.shaft_r_mm * 1.001),
        "annulus": _mask_stats(fields, args.shaft_r_mm * 0.999, rr * 1.001),
        "rim": _mask_stats(fields, rr * 0.95, rr * 1.001),
    }
    res["_region_method"] = (
        "radial bands on sqrt(x^2+y^2) -- the reader route carries no component or "
        "material identity, so 'rotor lamination' vs 'magnet' cannot be separated "
        "without the MAPDL database.  Bands are [0, r_shaft], [r_shaft, r_rotor], "
        "[0.95*r_rotor, r_rotor].")

    # 공극을 잡아먹는 것은 **외경(rim)** 의 반경변위이지 전역 최대가 아니다.
    # 자유-자유 원환에서는 보어 쪽 u_r 이 더 크기 때문에(u_r(a) > u_r(b)) 전역 최대를
    # 쓰면 공극 소모를 과대평가한다.
    rim_ur = res["per_region"]["rim"].get("max_ur_mm")
    res["max_rim_radial_disp_mm"] = rim_ur
    ur_for_gap = rim_ur if rim_ur is not None else res["max_radial_disp_mm"]
    res["airgap_consumed_pct"] = (100.0 * ur_for_gap / args.airgap_mm
                                  if args.airgap_mm > 0 else None)
    res["airgap_consumed_basis"] = ("max u_r over the rim band "
                                    "[0.95*r_rotor, r_rotor]"
                                    if rim_ur is not None else "global max u_r")
    res["yield_MPa"] = args.yield_MPa
    res["safety_factor"] = (None if args.yield_MPa is None
                            else float(args.yield_MPa) / res["max_von_mises_MPa"])
    res["safety_factor_note"] = (
        "safety_factor = yield_MPa / max_von_mises_MPa.  20PN1150F yield strength is "
        "NOT known -- Motor-CAD's 305 MPa (ActiveXParametersMotorCADv261.txt #5007) is "
        "a program default, not a datasheet value for this steel.  The thesis side "
        "fills this in (PLAN D6 TODO (i)); pass --yield-MPa to compute it here.")

    log("  max von Mises   : %.4f MPa at node %d  (x %.3f, y %.3f, z %.3f mm, "
        "r %.3f mm, theta %.2f deg)"
        % (res["max_von_mises_MPa"], res["max_von_mises_node"],
           res["max_von_mises_loc_mm"]["x"], res["max_von_mises_loc_mm"]["y"],
           res["max_von_mises_loc_mm"]["z"], res["max_von_mises_loc_mm"]["r"],
           res["max_von_mises_loc_mm"]["theta_deg"]))
    pct = res["airgap_consumed_pct"]
    log("  max radial disp : %.6f mm at node %d  (r %.3f mm) -> %.2f %% of the "
        "%.2f mm airgap"
        % (res["max_radial_disp_mm"], res["max_radial_disp_node"],
           res["max_radial_disp_loc_mm"]["r"],
           float("nan") if pct is None else pct, args.airgap_mm))
    return res


# =========================================================================== #
# 10. 속도 스윕                                                                 #
# =========================================================================== #

def build_sweep(rated, args, sweep_rpm, method, ana_fn, log, resolved=None):
    """4 점 스윕.  method='scale' 이면 omega^2 스케일, 'resolve' 면 실제 솔브 결과."""
    pts = []
    for rpm in sweep_rpm:
        sc = omega2_scale(rpm, args.rpm)
        ana = ana_fn(rpm)
        p = {
            "rpm": float(rpm),
            "omega_rad_s": omega_rad_s(rpm),
            "scale_n2": sc,
            "hoop_analytic_inner_MPa": ana["sigma_theta_inner_MPa"],
            "hoop_analytic_outer_MPa": ana["sigma_theta_outer_MPa"],
            "ur_analytic_outer_mm": ana["u_r_outer_mm"],
        }
        if method == "resolve" and resolved and float(rpm) in resolved:
            r = resolved[float(rpm)]
            p["max_von_mises_MPa"] = r["max_von_mises_MPa"]
            p["max_radial_disp_mm"] = r["max_radial_disp_mm"]
            p["max_von_mises_node"] = r["max_von_mises_node"]
            p["max_radial_disp_node"] = r["max_radial_disp_node"]
            p["source"] = "direct MAPDL solve"
        else:
            p["max_von_mises_MPa"] = rated["max_von_mises_MPa"] * sc
            p["max_radial_disp_mm"] = rated["max_radial_disp_mm"] * sc
            p["max_von_mises_node"] = rated["max_von_mises_node"]
            p["max_radial_disp_node"] = rated["max_radial_disp_node"]
            p["source"] = ("omega^2 scaling from %.0f rpm" % args.rpm)
        p["yield_MPa"] = args.yield_MPa
        p["safety_factor"] = (None if args.yield_MPa is None
                              else float(args.yield_MPa) / p["max_von_mises_MPa"])
        pts.append(p)
        log("    %6.0f rpm  w=%10.4f rad/s  (n/n_ref)^2=%.6f  svm=%10.4f MPa  "
            "d_r=%.6f mm  [%s]"
            % (p["rpm"], p["omega_rad_s"], p["scale_n2"],
               p["max_von_mises_MPa"], p["max_radial_disp_mm"], p["source"]))

    out = {
        "_method": ("resolve" if method == "resolve"
                    else "analytic_omega2_scaling_from_%.0frpm" % args.rpm),
        "_method_requested": method,
        "_method_options": ["resolve", "analytic_omega2_scaling_from_<ref>rpm"],
        "_reference_rpm": float(args.rpm),
        "_scaling_identity": ("sigma(n) = sigma(n_ref)*(n/n_ref)^2 and "
                              "delta_r(n) = delta_r(n_ref)*(n/n_ref)^2 -- EXACT, not "
                              "an approximation, for a linear elastic body under a "
                              "pure centrifugal body load with homogeneous "
                              "displacement BCs."),
        "_scaling_valid_if": ("linear elastic material; bonded (not frictional) "
                              "contact; no interference fit / sleeve / banding / "
                              "thermal preload; NLGEOM and spin softening off"),
        "_scaling_invalid_for": ("frictional contact (open/close state changes with "
                                 "speed), any plasticity, and ANY Neuber/Glinka "
                                 "plastic-corrected value -- scale the ELASTIC value "
                                 "first, then re-apply the correction at each speed"),
        "_c67_status": ("C67 has Sleeve_Thickness = Banding_Thickness = "
                        "Shaft_Hole_Diameter = 0 mm (Max3D L118-L120), so there is no "
                        "speed-independent constant term.  Whether the magnet-to-lam "
                        "interface is bonded or frictional (AdhesionFactor_Magnets = "
                        "0.2) decides whether the scaling is exact."),
        "points": pts,
    }
    return out


# =========================================================================== #
# 11. 그림                                                                      #
# =========================================================================== #

def _clim_for(arr, lo_pct, hi_pct):
    lo = _percentile(arr, lo_pct)
    hi = _percentile(arr, hi_pct)
    if _is_nan(lo) or _is_nan(hi) or hi <= lo:
        lo, hi = _nanmin(arr), _nanmax(arr)
    if _is_nan(lo) or _is_nan(hi) or hi <= lo:
        return None
    return [float(lo), float(hi)]


def _contour_pyvista(fields, key, bar_title, clim, cmap, log):
    """pyvista off_screen 렌더 -> RGB 배열.  실패하면 None (matplotlib 로 폴백)."""
    try:
        import pyvista as pv
    except Exception as exc:
        log("  pyvista unavailable (%s) -> matplotlib fallback" % exc)
        return None
    # pv.start_xvfb() 는 Linux 전용이다.  moa 는 Windows 이므로 절대 부르지 않는다.
    try:
        pv.OFF_SCREEN = True
        grid = fields.get("grid")
        arr = _np.asarray(fields[key], dtype=float)
        obj = None
        if grid is not None and hasattr(grid, "n_points"):
            if int(grid.n_points) == arr.size:
                obj = grid
            else:
                # 그리드 점 순서 != 필드 순서.  절점번호 배열이 있으면 재정렬해서
                # 살리고, 없으면 점구름으로 내려간다 (그림만 거칠어질 뿐 값은 같다).
                try:
                    gnum = None
                    for k in ("ansys_node_num", "node_num", "NodeIds"):
                        if k in grid.point_data:
                            gnum = _np.asarray(grid.point_data[k])
                            break
                    if gnum is not None and gnum.size == int(grid.n_points):
                        arr = _align_to(gnum, fields["nnum"], arr, 1, log=log,
                                        label="grid remap")
                        obj = grid
                        log("  pyvista: remapped the field onto the grid by node id")
                except Exception as exc:
                    log("  pyvista: grid remap failed (%s)" % str(exc)[:120])
            if obj is None:
                log("  pyvista: grid n_points (%d) != field length (%d) -> point "
                    "cloud" % (int(grid.n_points), arr.size))
        point_cloud = obj is None
        if point_cloud:
            obj = pv.PolyData(_np.asarray(fields["xyz_mm"], dtype=float))
        obj = obj.copy()
        obj[bar_title] = _np.asarray(arr, dtype=float)
        pl = pv.Plotter(off_screen=True, window_size=(900, 720))
        pl.set_background("white")
        kw = dict(scalars=bar_title, cmap=cmap, show_edges=False,
                  nan_opacity=0.0,
                  scalar_bar_args=dict(title=bar_title, vertical=True,
                                       title_font_size=14, label_font_size=11,
                                       color="black"))
        if clim:
            kw["clim"] = clim
        if point_cloud:
            kw["render_points_as_spheres"] = False
            kw["point_size"] = 3.0
        try:
            pl.add_mesh(obj, **kw)
        except TypeError as exc:
            # pyvista 버전 차이로 exotic kwarg 가 없을 수 있다 -> 최소 인자로 재시도.
            log("  pyvista: add_mesh(**kw) rejected (%s) -> minimal kwargs"
                % str(exc)[:120])
            kw2 = dict(scalars=bar_title, cmap=cmap, show_edges=False)
            if clim:
                kw2["clim"] = clim
            pl.add_mesh(obj, **kw2)
        pl.view_xy()
        pl.camera.zoom(1.25)
        img = pl.screenshot(return_img=True)
        pl.close()
        log("  pyvista: rendered %s (%dx%d)" % (bar_title, img.shape[1], img.shape[0]))
        return img
    except Exception as exc:
        log("  pyvista render failed (%s: %s) -> matplotlib fallback"
            % (type(exc).__name__, str(exc)[:160]))
        return None


def _contour_matplotlib(ts, fields, key, title, bar_title, path, clim, cmap,
                        args, log):
    """xy 투영 산점 컨투어.  값이 큰 절점이 위에 오도록 정렬해서 그린다."""
    import matplotlib.pyplot as plt

    x = _np.asarray([p[0] for p in fields["xyz_mm"]], dtype=float) \
        if not isinstance(fields["xyz_mm"], _np.ndarray) \
        else fields["xyz_mm"][:, 0]
    y = _np.asarray([p[1] for p in fields["xyz_mm"]], dtype=float) \
        if not isinstance(fields["xyz_mm"], _np.ndarray) \
        else fields["xyz_mm"][:, 1]
    v = _np.asarray(fields[key], dtype=float)

    ok = _np.isfinite(v)
    x, y, v = x[ok], y[ok], v[ok]
    n_max = int(args.max_plot_nodes)
    n_plotted = int(v.size)
    if v.size > n_max:
        step = int(math.ceil(v.size / float(n_max)))
        x, y, v = x[::step], y[::step], v[::step]
        n_plotted = int(v.size)
        log("  matplotlib: subsampled every %d-th node -> %d plotted"
            % (step, n_plotted))
    order = _np.argsort(v)             # 큰 값이 마지막에 그려져 위로 온다
    x, y, v = x[order], y[order], v[order]

    fig, ax = plt.subplots(figsize=ts.FIGSIZE["raster"])
    sc = ax.scatter(x, y, c=v, s=float(args.marker_size), cmap=cmap, linewidths=0,
                    vmin=(clim[0] if clim else None),
                    vmax=(clim[1] if clim else None))
    ax.set_aspect("equal")
    ax.set_xlabel(ts.check_label("x [mm]"))
    ax.set_ylabel(ts.check_label("y [mm]"))
    ax.set_title(ts.check_label(title), fontsize=10, color=ts.INK, pad=6)
    cb = fig.colorbar(sc, ax=ax, fraction=0.046, pad=0.03)
    cb.set_label(ts.check_label(bar_title))
    fig.tight_layout(pad=0.3)
    res = ts.savefig_guarded(fig, path, dpi=float(args.contour_dpi),
                             max_bytes=int(args.png_max_kb) * 1024)
    plt.close(fig)
    res["backend"] = "matplotlib scatter (xy projection, value-sorted)"
    res["n_plotted"] = n_plotted
    return res


def make_contour(ts, fields, key, title, bar_title, path, cmap, args, log):
    clim = _clim_for(fields[key], float(args.clim_lo_pct), float(args.clim_hi_pct))
    log("  %s: clim = %s" % (os.path.basename(path),
                             "auto-none" if clim is None
                             else "[%.4g, %.4g]" % (clim[0], clim[1])))
    img = None
    if not args.no_pyvista:
        img = _contour_pyvista(fields, key, bar_title, clim, cmap, log)
    if img is not None:
        # VTK 는 한글을 못 그린다 -> 제목은 matplotlib 이 붙인다.
        res = ts.png_from_pyvista(img, title, path, dpi=float(args.contour_dpi),
                                  max_bytes=int(args.png_max_kb) * 1024)
        res["backend"] = "pyvista off_screen + matplotlib title composite"
        res["n_plotted"] = int(len(fields[key]))
    else:
        res = _contour_matplotlib(ts, fields, key, title, bar_title, path, clim,
                                  cmap, args, log)
    res["clim"] = clim
    res["cmap"] = cmap
    log("  wrote %s  (%d B, dpi %.0f, %s, backend=%s)"
        % (res["path"], res["bytes"], res["dpi"],
           "OK" if res["ok"] else "OVER LIMIT", res["backend"]))
    if not res["ok"]:
        log("  WARN: %s exceeds %d KB even after the dpi/palette ladder"
            % (res["path"], int(args.png_max_kb)))
    return res


def make_sweep_figure(ts, sweep, ana_fn, path, args, log):
    """속도 스윕 2 패널 (최대 von Mises / 최대 반경변위)."""
    import matplotlib.pyplot as plt

    pts = sweep["points"]
    n = [p["rpm"] for p in pts]
    s = [p["max_von_mises_MPa"] for p in pts]
    d = [p["max_radial_disp_mm"] for p in pts]
    ha = [p["hoop_analytic_inner_MPa"] for p in pts]
    ua = [p["ur_analytic_outer_mm"] for p in pts]

    col = ts.CASE_COLORS["AC"]
    fig, axes = plt.subplots(1, 2, figsize=ts.FIGSIZE["wide2panel"])
    ax = axes[0]
    ax.plot(n, s, "-o", color=col, markersize=4.5, markerfacecolor="white",
            markeredgewidth=1.2, label=ts.check_label("FE 최대"))
    ax.plot(n, ha, "--", color=ts.INK2, linewidth=1.1,
            label=ts.check_label("해석해 보어 후프"))
    ax.set_xlabel(ts.check_label("회전속도 [rpm]"))
    ax.set_ylabel(ts.check_label("최대 폰미제스 응력 [MPa]"))
    ax.legend(fontsize=8, frameon=False)

    ax = axes[1]
    ax.plot(n, d, "-o", color=col, markersize=4.5, markerfacecolor="white",
            markeredgewidth=1.2, label=ts.check_label("FE 최대"))
    ax.plot(n, ua, "--", color=ts.INK2, linewidth=1.1,
            label=ts.check_label("해석해 외경"))
    # 공극선(0.8 mm)은 변위(수십 um)보다 한 자릿수 크다.  그냥 그리면 곡선이
    # 바닥에 눌려 아무것도 안 보인다 -> 실제로 근접했을 때만 선을 긋고,
    # 아니면 소모율을 글자로 적는다.
    d_max = max(d)
    if args.airgap_mm > 0 and d_max >= 0.15 * args.airgap_mm:
        ax.axhline(args.airgap_mm, color=ts.LIMIT_COLOR, linewidth=1.0,
                   linestyle=":", label=ts.check_label("공극 %.1f mm" % args.airgap_mm))
    elif args.airgap_mm > 0:
        ax.text(0.03, 0.93, ts.check_label(
            "공극 %.1f mm 대비 최대 %.1f %%" % (args.airgap_mm,
                                             100.0 * d_max / args.airgap_mm)),
                transform=ax.transAxes, fontsize=8, color=ts.INK2, va="top")
    ax.set_xlabel(ts.check_label("회전속도 [rpm]"))
    ax.set_ylabel(ts.check_label("최대 반경방향 변위 [mm]"))
    ax.legend(fontsize=8, frameon=False)

    for ax in axes:
        ax.set_xticks(n)
        ax.set_xticklabels(["{:,}".format(int(v)) for v in n])
        ax.grid(True, color=ts.GRIDC, linewidth=0.6)
        ax.set_axisbelow(True)

    if sweep["_method"] == "resolve":
        sub = "MAPDL 재솔브 %d점" % len(pts)
    else:
        sub = "omega^2 스케일, %s rpm 기준" % "{:,}".format(int(sweep["_reference_rpm"]))
    fig.suptitle(ts.check_label("C67 회전자 원심 응력 - 속도 스윕 (%s)" % sub),
                 fontsize=10, color=ts.INK)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    res = ts.savefig_guarded(fig, path, dpi=args.dpi,
                             max_bytes=int(args.png_max_kb) * 1024)
    plt.close(fig)
    res["backend"] = "matplotlib"
    log("  wrote %s  (%d B, dpi %.0f, %s)"
        % (res["path"], res["bytes"], res["dpi"], "OK" if res["ok"] else "OVER LIMIT"))
    return res


# =========================================================================== #
# 12. git / 파일 유틸                                                           #
# =========================================================================== #

def rel_to_repo(path, repo):
    """repo 기준 상대경로.  다른 드라이브면 relpath 가 ValueError 를 던지므로
    (Windows 에서 흔하다 -- 레포 E:\\, 출력 C:\\) 절대경로로 폴백한다."""
    try:
        return os.path.relpath(path, repo).replace("\\", "/")
    except ValueError:
        return os.path.abspath(path).replace("\\", "/")


def sha256_of(path, max_bytes=None):
    h = hashlib.sha256()
    n = 0
    with open(path, "rb") as f:
        while True:
            b = f.read(1 << 20)
            if not b:
                break
            h.update(b)
            n += len(b)
            if max_bytes and n >= max_bytes:
                break
    return h.hexdigest()


def check_gitignore(paths, repo, log):
    """.gitignore:39 `*.png` 가 thesis_out PNG 를 조용히 삼킨다 -- 커밋 전에 경고.

    고치는 방법은 루트 .gitignore 맨 끝에 negation 한 줄:
        !mlxperPJT/thermal/thesis_out/*.png
    이 파일은 plans/ 밖이므로 **moa 가** 적용한다.  임시 회피는 `git add -f`.
    """
    out = {"checked": [], "ignored": [], "skipped": [], "git_available": False,
           "fix_patch": "!mlxperPJT/thermal/thesis_out/*.png",
           "fix_note": ("append the line above to the ROOT .gitignore (it lives "
                        "outside plans/, so moa applies it), or commit with "
                        "`git add -f <png>`; verify with `git ls-files`")}
    for p in paths:
        if not p:
            continue
        out["checked"].append(p)
        try:
            # ** verdict WITHOUT -v **. With -v, git check-ignore exits 0 whenever ANY
            # pattern matched -- including a NEGATION (!...). Once .gitignore carries
            # `!mlxperPJT/thermal/thesis_out/*.png`, the -v form reports a perfectly
            # committable PNG as ignored. Measured on moa 2026-09-07: -q -> exit 1
            # (committable), -v -> exit 0 (ignored), same file. -v is used afterwards
            # only to fetch the rule text.
            r = subprocess.run(["git", "-C", repo, "check-ignore", p],
                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            out["git_available"] = True
            # git check-ignore exit codes: 0 = ignored, 1 = NOT ignored,
            # anything else (128) = the question was never asked -- the path is
            # outside the repo, or this is not a git work tree.  Reporting 128 as
            # "not ignored" would be a false all-clear, so it is a SKIP, not a pass.
            if r.returncode == 0:
                _v = subprocess.run(["git", "-C", repo, "check-ignore", "-v", p],
                                    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                rule = _v.stdout.decode("utf-8", "replace").strip()
                out["ignored"].append({"path": p, "rule": rule})
                log("  GITIGNORE WARN: %s is ignored by %s" % (os.path.basename(p),
                                                               rule))
            elif r.returncode != 1:
                why = r.stderr.decode("utf-8", "replace").strip().splitlines()
                why = why[0] if why else "git exit %d" % r.returncode
                out["skipped"].append({"path": p, "reason": why})
        except Exception as exc:
            log("  git check-ignore unavailable (%s)" % exc)
            break
    if out["ignored"]:
        log("  => %d output file(s) will NOT be committed as-is.  Fix: append"
            % len(out["ignored"]))
        log("     %s" % out["fix_patch"])
        log("     to the ROOT .gitignore, or use `git add -f`.")
    if out["skipped"]:
        log("  git check-ignore SKIPPED for %d of %d path(s) -- NOT an all-clear: %s"
            % (len(out["skipped"]), len(out["checked"]),
               out["skipped"][0]["reason"]))
        log("     (these outputs are outside the repo, so this run tells you nothing")
        log("      about whether thesis_out PNGs would be committed. Re-check with")
        log("      --out inside the repo before the promotion commit.)")
    if out["git_available"] and not out["ignored"] and not out["skipped"]:
        log("  git check-ignore: no output file is ignored")
    return out


# =========================================================================== #
# 13. main                                                                      #
# =========================================================================== #

def default_repo_root():
    """kit dir = <repo>/mlxperPJT/thermal/plans/PLAN_20260906_assets -> parents[4]."""
    here = os.path.abspath(os.path.dirname(__file__))
    p = here
    for _ in range(4):
        p = os.path.dirname(p)
    return p


def build_parser():
    p = argparse.ArgumentParser(
        prog="d6_c67_stress.py",
        description="D6: C67 rotor centrifugal stress extraction "
                    "(von Mises + radial displacement + 4-point speed sweep).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="See the module docstring: 251114_C67_test_Moa_Max3D.py is a Maxwell 3D "
               "ELECTROMAGNETIC build script and cannot regenerate the .rst.")
    p.add_argument("--rst", default=None,
                   help="path to file.rst (Workbench <proj>_files/dp0/SYS-5/MECH/)")
    p.add_argument("--mech-dir", default=None,
                   help="the whole MECH folder (enables --sweep-method resolve; "
                        "MAPDL /POST1 cannot read a lone .rst)")
    p.add_argument("--out", default=None,
                   help="output directory (default <repo>/mlxperPJT/thermal/thesis_out)")
    p.add_argument("--out-json", default=None,
                   help="output JSON path (default <out>/c67_stress.json)")
    p.add_argument("--log", default=None,
                   help="log file (default <out>/d6_c67_stress.log)")
    p.add_argument("--repo", default=default_repo_root(),
                   help="repo root (default: resolved from this file's location)")
    p.add_argument("--rpm", type=float, default=RPM_DEFAULT,
                   help="rated speed of the reference solve (default 18000)")
    p.add_argument("--sweep", default=SWEEP_DEFAULT,
                   help="comma separated rpm list (default %s)" % SWEEP_DEFAULT)
    p.add_argument("--sweep-method", choices=["scale", "resolve"], default=None,
                   help="default: 'scale' when only --rst is available, "
                        "'resolve' when --mech-dir is given")
    p.add_argument("--reader", choices=["auto", "dpf", "mapdl_reader", "mapdl"],
                   default="auto",
                   help="result reader; auto probes dpf -> mapdl_reader -> mapdl")
    p.add_argument("--dry-run", action="store_true",
                   help="no Ansys: analytic gate + omega conversion + omega^2 "
                        "scaling + JSON/PNG writing with a synthetic field")

    g = p.add_argument_group("geometry / material (all recorded in the JSON)")
    g.add_argument("--shaft-r-mm", type=float, default=R_SHAFT_MM_DEFAULT)
    g.add_argument("--rotor-r-mm", type=float, default=R_ROTOR_MM_DEFAULT)
    g.add_argument("--airgap-mm", type=float, default=AIRGAP_MM_DEFAULT)
    g.add_argument("--stack-mm", type=float, default=STACK_MM_DEFAULT)
    g.add_argument("--rho", type=float, default=RHO_DEFAULT)
    g.add_argument("--E-GPa", type=float, default=E_GPA_DEFAULT)
    g.add_argument("--poisson", type=float, default=POISSON_DEFAULT)
    g.add_argument("--mu", type=float, default=MU_DEFAULT)
    g.add_argument("--contact", default=CONTACT_DEFAULT)
    g.add_argument("--element-mm", type=float, default=ELEMENT_MM_DEFAULT)
    g.add_argument("--yield-MPa", type=float, default=YIELD_MPA_DEFAULT,
                   help="20PN1150F yield strength.  UNKNOWN by default -> the JSON "
                        "writes null.  Motor-CAD's 305 MPa is a program default, not "
                        "a datasheet value: do not pass it as if it were measured.")

    f = p.add_argument_group("figures")
    f.add_argument("--no-figures", action="store_true")
    f.add_argument("--no-pyvista", action="store_true",
                   help="skip pyvista and go straight to the matplotlib fallback")
    f.add_argument("--cmap", default="jet",
                   help="contour colormap (repo convention 'jet'; use 'viridis' for "
                        "a greyscale-safe print)")
    f.add_argument("--dpi", type=float, default=300.0,
                   help="dpi for the line-chart figure (measured: 300 fits 300 KB)")
    f.add_argument("--contour-dpi", type=float, default=150.0,
                   help="dpi for the two contour rasters.  300 does NOT fit 300 KB "
                        "for a dense scatter/screenshot; savefig_guarded would spend "
                        "seconds walking its dpi/palette ladder down to ~157 anyway.")
    f.add_argument("--png-max-kb", type=int, default=300)
    f.add_argument("--clim-lo-pct", type=float, default=0.0)
    f.add_argument("--clim-hi-pct", type=float, default=99.9,
                   help="upper contour clim percentile (99.9 keeps a single bridge "
                        "singularity from flattening the whole map)")
    f.add_argument("--max-plot-nodes", type=int, default=250000)
    f.add_argument("--marker-size", type=float, default=1.2)

    d = p.add_argument_group("dry-run synthetic field")
    d.add_argument("--dry-run-kt", type=float, default=3.0,
                   help="synthetic bridge stress concentration factor (3.0 lands in "
                        "the expected 2-4x band; pass 1.0 to exercise the WARN path)")
    d.add_argument("--dry-run-nr", type=int, default=40)
    d.add_argument("--dry-run-nt", type=int, default=180)
    d.add_argument("--dry-run-nz", type=int, default=3)

    m = p.add_argument_group("MAPDL (resolve route only)")
    m.add_argument("--mapdl-nproc", type=int, default=4)
    m.add_argument("--mapdl-memory", type=int, default=None)
    m.add_argument("--mapdl-run-dir", default=None)
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)

    repo = os.path.abspath(args.repo)
    out_dir = args.out or os.path.join(repo, "mlxperPJT", "thermal", "thesis_out")
    out_dir = os.path.abspath(out_dir)
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    stem = "c67_stress" + (".dryrun" if args.dry_run else "")
    out_json = args.out_json or os.path.join(out_dir, stem + ".json")
    log_path = args.log or os.path.join(out_dir, "d6_c67_stress.log")

    log = Log(log_path)
    t_start = time.time()
    warnings_all = []
    try:
        log.rule("D6 -- C67 rotor centrifugal stress")
        log("repo      : %s" % repo)
        log("out dir   : %s" % out_dir)
        log("out json  : %s" % out_json)
        log("log       : %s" % log_path)
        log("python    : %s" % sys.version.split()[0])
        log("rated rpm : %.1f  -> omega %.10f rad/s"
            % (args.rpm, omega_rad_s(args.rpm)))

        sweep_rpm = [float(s) for s in str(args.sweep).replace(" ", "").split(",")
                     if s]
        log("sweep rpm : %s" % ", ".join("%.0f" % v for v in sweep_rpm))

        # ---- (a) 해석해 공식 자체 검증 -- Ansys 없이 무조건 돈다 --------------
        log.rule("analytic annulus formula self-check (18 krpm reference)")
        formula_checks = verify_analytic_formula(log)

        def ana_fn(rpm):
            return annulus_plane_stress(rpm, args.shaft_r_mm / 1000.0,
                                        args.rotor_r_mm / 1000.0, args.poisson,
                                        args.rho, args.E_GPa * 1e9)

        ana_rated = ana_fn(args.rpm)

        # ---- (b) 소스 결정 ---------------------------------------------------
        log.rule("source / reader")
        avail = probe_readers(log)
        rst = args.rst
        mech_dir = args.mech_dir
        if mech_dir:
            mech_dir = os.path.abspath(mech_dir)
            if not os.path.isdir(mech_dir):
                raise RuntimeError("--mech-dir does not exist: %s" % mech_dir)
            if not rst:
                cand = os.path.join(mech_dir, "file.rst")
                if os.path.isfile(cand):
                    rst = cand
                    log("  found %s inside --mech-dir" % cand)
        if rst:
            rst = os.path.abspath(rst)

        source = {"rst": rst, "mech_dir": mech_dir,
                  "probe": avail,
                  "reader": None, "reader_version": None,
                  "n_sets": None, "set_used": [1, 1],
                  "set_used_note": ("load step 1 / substep 1; the reader APIs are "
                                    "0-based (rsets index 0), MAPDL SET is 1-based")}

        if args.dry_run:
            route = "dry-run-synthetic"
            log("  ROUTE: --dry-run -> synthetic analytic field, no Ansys touched")
            raw = synthetic_fields(args, log)
        elif rst:
            if not os.path.isfile(rst):
                raise RuntimeError(
                    "rst not found: %s\n"
                    "  The C67 rst lives on the thesis PC at\n"
                    "  E:/KDH/251114_C67_test/C67_stress_files/dp0/SYS-5/MECH/file.rst\n"
                    "  Copy the WHOLE MECH folder to moa (a lone rst blocks the MAPDL "
                    "route), or re-solve C67_stress.wbpj, or fall back to the "
                    "Motor-CAD .mot route (tools/motorCAD/pyMCAD/stress.py)." % rst)
            route = "rst"
            source["rst_bytes"] = os.path.getsize(rst)
            log("  rst: %s (%.1f MB)" % (rst, source["rst_bytes"] / 1048576.0))
            source["rst_sha256"] = sha256_of(rst)
            log("  rst sha256: %s" % source["rst_sha256"])
            cands = pick_reader(args.reader, avail, log)
            raw, errs = None, []
            for which in cands:
                try:
                    log("  trying reader '%s'" % which)
                    if which == "dpf":
                        raw = read_rst_dpf(rst, log)
                    else:
                        raw = read_rst_mapdl_reader(rst, log)
                    source["reader_version"] = avail.get(which)
                    break
                except Exception as exc:
                    msg = "%s: %s" % (type(exc).__name__, str(exc)[:220])
                    errs.append({"reader": which, "error": msg})
                    warnings_all.append("reader '%s' failed (%s)" % (which, msg))
                    log("  WARN: reader '%s' failed -> %s" % (which, msg))
            source["reader_attempts"] = errs
            if raw is None:
                raise RuntimeError(
                    "every available reader failed on %s: %s\n"
                    "  ansys.mapdl.core alone cannot read a lone .rst -- pass "
                    "--mech-dir with ds.dat / file.db / a .cdb to re-solve instead."
                    % (rst, errs))
        elif mech_dir:
            route = "mapdl_resolve"
            log("  ROUTE: no rst -> MAPDL re-solve from the MECH database at %.0f rpm"
                % args.rpm)
            solved = solve_rst_mapdl(mech_dir, [args.rpm], log,
                                     nproc=args.mapdl_nproc,
                                     memory=args.mapdl_memory,
                                     run_dir=args.mapdl_run_dir)
            raw = solved[float(args.rpm)]
            raw["reader"] = "ansys.mapdl.core (live /POST1 after re-solve)"
            raw["averaging"] = "nodal_eqv_stress() (MAPDL nodal averaged)"
            raw["n_sets"] = 1
        else:
            raise RuntimeError("nothing to read: pass --rst, --mech-dir, or --dry-run")

        source["route"] = route
        source["reader"] = raw.get("reader")
        source["n_sets"] = raw.get("n_sets")
        source["averaging"] = raw.get("averaging")
        # 2D vs 3D matters for the reader: a Motor-CAD mechanical result is a 2D plane
        # model (2 DOF/node), so uz is absent and padded with zeros.  Record it so the
        # thesis side knows the displacement field is planar.
        source["model_dim"] = raw.get("model_dim", "unknown")

        # ---- (c) 단위 판별 + 파생 --------------------------------------------
        log.rule("units / derived fields")
        s_scale, s_native = infer_stress_scale(_nanmaxabs(raw["svm_raw"]), log)
        l_scale, l_native = infer_length_scale(_nanmaxabs(raw["xyz_raw"]), log)

        if _np is not None and isinstance(raw["svm_raw"], _np.ndarray):
            svm = raw["svm_raw"] * s_scale
            xyz = raw["xyz_raw"] * l_scale
            u = raw["u_raw"] * l_scale
        else:
            svm = [v * s_scale for v in raw["svm_raw"]]
            xyz = [[c * l_scale for c in row] for row in raw["xyz_raw"]]
            u = [[c * l_scale for c in row] for row in raw["u_raw"]]

        fields = {"nnum": raw["nnum"], "xyz_mm": xyz, "svm_MPa": svm, "u_mm": u,
                  "grid": raw.get("grid")}
        derive_fields(fields, log)

        r_max = _nanmax(fields["r_mm"])
        log("  geometry check: max radius = %.4f mm (expected ~%.1f mm)"
            % (r_max, args.rotor_r_mm))
        if abs(r_max - args.rotor_r_mm) > 0.10 * args.rotor_r_mm:
            w = ("max nodal radius %.4f mm differs from the expected rotor radius "
                 "%.2f mm by more than 10%% -- wrong model, wrong unit, or a "
                 "different geometry" % (r_max, args.rotor_r_mm))
            warnings_all.append(w)
            log("  WARN: " + w)

        # ---- (d) 최대값 -------------------------------------------------------
        log.rule("maxima at the rated speed")
        rated = extract_maxima(fields, args, log)

        # ---- (e) sanity 게이트 ------------------------------------------------
        log.rule("analytic sanity gate")
        gate = sanity_gate(rated["max_von_mises_MPa"], rated["max_radial_disp_mm"],
                           args.rpm, ana_rated, log)
        warnings_all.extend(gate["warnings"])

        # ---- (f) 스윕 ---------------------------------------------------------
        log.rule("speed sweep")
        method = args.sweep_method
        if method is None:
            # Default to 'scale' whenever a reference result was actually read.
            # omega^2 scaling is EXACT for a linear elastic body under a pure centrifugal
            # load, and it cannot double-apply the rotational velocity.  A Workbench
            # ds.dat usually already carries its own rotational velocity, so re-solving
            # with an added OMEGA superposes the two and inflates stress by (2w)^2/w^2 = 4x.
            # Observed on C67 SYS-5: rst 499 MPa vs re-solve 1996 MPa at the same 18 krpm.
            method = "scale"
            log("  --sweep-method not given -> defaulting to 'scale' "
                "(omega^2 from the reference solve; exact for linear elastic + bonded, "
                "and immune to the ds.dat double-OMEGA trap). "
                "Pass --sweep-method resolve to force a real re-solve.")
        resolved = None
        if method == "resolve":
            if args.dry_run:
                method = "scale"
                log("  --dry-run cannot re-solve -> falling back to 'scale'")
            elif not mech_dir:
                method = "scale"
                w = ("--sweep-method resolve needs --mech-dir (a lone .rst cannot be "
                     "re-solved) -> falling back to omega^2 scaling")
                warnings_all.append(w)
                log("  WARN: " + w)
            else:
                try:
                    solved = solve_rst_mapdl(mech_dir, sweep_rpm, log,
                                             nproc=args.mapdl_nproc,
                                             memory=args.mapdl_memory,
                                             run_dir=args.mapdl_run_dir)
                    resolved = {}
                    for rpm, rr in solved.items():
                        ss, _ = infer_stress_scale(_nanmaxabs(rr["svm_raw"]), log)
                        ll, _ = infer_length_scale(_nanmaxabs(rr["xyz_raw"]), log)
                        ff = {"nnum": rr["nnum"], "xyz_mm": rr["xyz_raw"] * ll,
                              "svm_MPa": rr["svm_raw"] * ss,
                              "u_mm": rr["u_raw"] * ll, "grid": None}
                        derive_fields(ff, log)
                        a2 = argparse.Namespace(**vars(args))
                        a2.rpm = rpm
                        resolved[float(rpm)] = extract_maxima(ff, a2, log)
                except Exception as exc:
                    method = "scale"
                    w = ("MAPDL re-solve sweep failed (%s: %s) -> falling back to "
                         "omega^2 scaling" % (type(exc).__name__, str(exc)[:220]))
                    warnings_all.append(w)
                    log("  WARN: " + w)

                # Cross-check the re-solve against the reference result at the SAME rpm.
                # They must agree.  A ratio near 4 means the deck already carried its own
                # rotational velocity and our OMEGA superposed on it ((2w)^2/w^2 = 4).
                if resolved:
                    ref_rpm = float(args.rpm)
                    match = None
                    for k in resolved:
                        if abs(k - ref_rpm) < 1e-6:
                            match = resolved[k]
                            break
                    if match is not None:
                        try:
                            a = float(rated["von_mises_max_MPa"])
                            b = float(match["von_mises_max_MPa"])
                            ratio = (b / a) if a else float("nan")
                            log("  re-solve cross-check @%.0f rpm: reference %.4f MPa vs "
                                "re-solve %.4f MPa (ratio %.3f)" % (ref_rpm, a, b, ratio))
                            if not (0.95 <= ratio <= 1.05):
                                w = ("re-solve DISAGREES with the reference result at the same "
                                     "%.0f rpm: %.4f vs %.4f MPa (ratio %.3f). A ratio near 4.0 "
                                     "means ds.dat already defines a rotational velocity and the "
                                     "re-solve added another on top. Use --sweep-method scale, or "
                                     "zero the existing OMEGA in the deck."
                                     % (ref_rpm, a, b, ratio))
                                warnings_all.append(w)
                                log("  WARN: " + w)
                        except Exception:
                            pass
        if method == "scale":
            log("  omega^2 scaling from the %.0f rpm solve.  This is EXACT for a "
                "linear elastic body under a pure centrifugal load with bonded "
                "contact; it is INVALID for frictional contact or any plasticity "
                "(Neuber/Glinka) correction." % args.rpm)
        sweep = build_sweep(rated, args, sweep_rpm, method, ana_fn, log,
                            resolved=resolved)

        # ---- (g) 그림 ---------------------------------------------------------
        figures = {}
        fig_meta = {}
        if args.no_figures:
            log.rule("figures skipped (--no-figures)")
        elif _np is None:
            log.rule("figures skipped (numpy unavailable)")
            warnings_all.append("numpy unavailable -> figures skipped")
        else:
            log.rule("figures")
            try:
                import thesis_style as ts
                ts.apply()
                log("  thesis_style font: %s" % ts.active_font())
                with ts.glyph_watch() as gw:
                    p_vm = os.path.join(out_dir, stem + "_vonmises.png")
                    p_ur = os.path.join(out_dir, stem + "_ur.png")
                    p_sw = os.path.join(out_dir, stem + "_vs_speed.png")
                    fig_meta["von_mises"] = make_contour(
                        ts, fields, "svm_MPa",
                        "C67 회전자 원심 응력 - 폰미제스 [MPa], %s rpm"
                        % "{:,}".format(int(args.rpm)),
                        "von Mises [MPa]", p_vm, args.cmap, args, log)
                    fig_meta["radial_disp"] = make_contour(
                        ts, fields, "u_r_mm",
                        "C67 회전자 반경방향 변위 [mm], %s rpm"
                        % "{:,}".format(int(args.rpm)),
                        "radial disp [mm]", p_ur, args.cmap, args, log)
                    fig_meta["sweep"] = make_sweep_figure(ts, sweep, ana_fn, p_sw,
                                                          args, log)
                for k, v in fig_meta.items():
                    figures[k] = rel_to_repo(v["path"], repo)
                if gw.count:
                    w = ("%d missing-glyph warning(s) during figure rendering: %s"
                         % (gw.count, gw.messages[:3]))
                    warnings_all.append(w)
                    log("  WARN: " + w)
                else:
                    log("  glyph_watch: 0 missing glyphs")
            except Exception as exc:
                w = ("figure generation failed (%s: %s)"
                     % (type(exc).__name__, str(exc)[:220]))
                warnings_all.append(w)
                log("  WARN: " + w)

        # ---- (h) gitignore 자가진단 -------------------------------------------
        log.rule("git check-ignore (thesis_out PNGs)")
        git_check = check_gitignore([v["path"] for v in fig_meta.values()]
                                    + [out_json], repo, log)

        # ---- (i) JSON ---------------------------------------------------------
        log.rule("JSON")
        doc = {
            "_soltype": "static",
            "_loss_source": "n/a (structural, centrifugal body load only)",
            "_htc": "n/a (structural)",
            "_model": ("C67 rotor centrifugal -- Workbench Static Structural "
                       "(dp0/SYS-5/MECH)"),
            "_generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "_script": ("mlxperPJT/thermal/plans/PLAN_20260906_assets/"
                        "d6_c67_stress.py"),
            "_argv": list(sys.argv[1:]),
            "_python": sys.version.split()[0],
            "_wallclock_s": None,
            "_source": source,
            "_units": {
                "stress": "MPa", "displacement": "mm", "length": "mm",
                "speed": "rpm", "omega": "rad/s",
                "native_stress_detected": s_native,
                "native_length_detected": l_native,
                "stress_scale_applied": s_scale,
                "length_scale_applied": l_scale,
            },
            "_model_meta": {
                "rpm": float(args.rpm),
                "omega_rad_s": omega_rad_s(args.rpm),
                "omega_formula": "omega = rpm*2*pi/60; MAPDL load = OMEGA,,,omega_z",
                "rotation_axis": ROTATION_AXIS,
                "rotation_center_mm": [0.0, 0.0, 0.0],
                "element_size_mm": float(args.element_mm),
                "element_size_source": ("MotorCAD MechanicalMeshLength_RotorLam "
                                        "(#4978) / WB Mesh Element Size -- CLI value, "
                                        "not read from the result file"),
                "contact": args.contact,
                "friction_or_adhesion_coefficient": float(args.mu),
                "contact_param_source": ("MotorCAD AdhesionFactor_Magnets "
                                         "(#4988, default 0.2) -- CLI value"),
                "E_GPa": float(args.E_GPa),
                "E_source": ("MotorCAD YoungsCoefficient_RotorLam = 192500 MPa "
                             "(RotorStress_e10.ipynb cell 15; pyMCAD2Maxwell.ipynb "
                             "cell 19)"),
                "poisson": float(args.poisson),
                "poisson_source": "MotorCAD PoissonsRatio_RotorLam (#5006)",
                "rho_kg_m3": float(args.rho),
                "rho_source": ("20PN1150F mass_density, "
                               "251114_C67_test_Moa_Max3D.py L237/L355; cross-checked "
                               "by KETI/Discovery.json Material Data.20pn1150f"),
                "rotor_lam_material": "20PN1150F",
                "magnet_material": "NEOREC48DUH",
                "magnet_rho_kg_m3": 7550.0,
                "rotor_OD_mm": float(args.rotor_r_mm) * 2.0,
                "shaft_dia_mm": float(args.shaft_r_mm) * 2.0,
                "airgap_mm": float(args.airgap_mm),
                "rotor_lam_length_mm": float(args.stack_mm),
                "poles": 8, "slots": 48,
                "L1_bridge_mm": 3.0, "L1_post_mm": 3.0,
                "L2_bridge_mm": 1.5, "L2_post_mm": 0.9,
                "sleeve_mm": 0.0, "banding_mm": 0.0, "shaft_hole_mm": 0.0,
                "geometry_source": "251114_C67_test_Moa_Max3D.py L54-L120",
                "yield_MPa": args.yield_MPa,
                "yield_MPa_source": ("UNKNOWN.  20PN1150F datasheet yield strength is "
                                     "not in this repo.  Motor-CAD's 305 MPa "
                                     "(#5007) is a program default placeholder -- do "
                                     "NOT record it as measured.  The thesis side "
                                     "fills this in (PLAN D6 TODO (i))."),
                "_meta_provenance": SOURCES_NOTE,
                "_meta_caveat": ("element size, contact, mu, E, nu and rho are CLI "
                                 "arguments echoed here for the record; a .rst does "
                                 "not carry them.  Only the MotorCAD route can read "
                                 "them back from the model."),
            },
            "at_rated": rated,
            "sweep": sweep,
            "figures": figures,
            "_figures_meta": _py(fig_meta),
            "_sanity": {
                "analytic": {
                    "a_mm": float(args.shaft_r_mm), "b_mm": float(args.rotor_r_mm),
                    "model": ("free-free rotating annulus, plane stress, "
                              "sigma_theta(a) = (3+nu)/4*rho*w^2*"
                              "[b^2 + (1-nu)/(3+nu)*a^2]"),
                    "sigma_theta_inner_MPa": ana_rated["sigma_theta_inner_MPa"],
                    "sigma_theta_outer_MPa": ana_rated["sigma_theta_outer_MPa"],
                    "u_r_outer_um": ana_rated["u_r_outer_um"],
                    "note": ana_rated["_note"],
                },
                "formula_self_check": formula_checks,
                "gate": gate,
            },
            "_blockers": {
                "max3d_script": ("251114_C67_test_Moa_Max3D.py is a Maxwell 3D "
                                 "TRANSIENT ELECTROMAGNETIC build script at 5600 rpm "
                                 "(header L1-L2, InsertDesign L27, MachineRPM L129).  "
                                 "It cannot regenerate this .rst -- do not try."),
                "mapdl_needs_db": ("MAPDL /POST1 cannot read a lone .rst; it needs "
                                   "file.db / a .cdb / ds.dat.  Copy the whole MECH "
                                   "folder.  ansys.mapdl.reader.read_binary CAN read "
                                   "a lone rst."),
                "dpf_absent": ("ansys.dpf.core has ZERO uses in this repo and is not "
                               "in the moa venv inventory.  It is probed, never "
                               "required."),
                "motorcad_fallback": ("if neither the rst nor the wbpj reaches moa, "
                                      "use tools/motorCAD/pyMCAD/stress.py + "
                                      "mlxperPJT/KETI/RotorStress_e10.ipynb with the "
                                      "C67 .mot: mc.set_variable('ShaftSpeed', n); "
                                      "mc.do_mechanical_calculation(); "
                                      "get_stress_data(mc) gives MaxStress_RotorLam / "
                                      "MaxDisplacement_RotorLam / "
                                      "SafetyFactor_RotorLam directly (2D plane "
                                      "stress -- label _soltype accordingly)."),
                "gitignore_png": git_check,
            },
            "_warnings": warnings_all,
        }
        doc["_sweep_method"] = sweep["_method"]
        doc["_wallclock_s"] = round(time.time() - t_start, 3)

        with open(out_json, "w", encoding="utf-8") as f:
            json.dump(_py(doc), f, ensure_ascii=False, indent=2)
            f.write("\n")
        log("  wrote %s (%d B)" % (out_json, os.path.getsize(out_json)))

        log.rule("summary")
        log("  route            : %s" % route)
        log("  reader           : %s" % source["reader"])
        log("  max von Mises    : %.4f MPa @ node %d"
            % (rated["max_von_mises_MPa"], rated["max_von_mises_node"]))
        log("  max radial disp  : %.6f mm @ node %d"
            % (rated["max_radial_disp_mm"], rated["max_radial_disp_node"]))
        log("  sanity gate      : %s" % ("PASS" if gate["passed"] else "WARN"))
        log("  sweep method     : %s" % sweep["_method"])
        log("  yield / SF       : %s / %s"
            % (rated["yield_MPa"], rated["safety_factor"]))
        log("  warnings         : %d" % len(warnings_all))
        for w in warnings_all:
            log("    - %s" % w)
        log("  json             : %s" % out_json)
        for k, v in figures.items():
            log("  fig %-14s : %s" % (k, v))
        log("  elapsed          : %.2f s" % (time.time() - t_start))
        return 0
    except Exception as exc:
        log("FATAL %s: %s" % (type(exc).__name__, exc))
        import traceback
        for line in traceback.format_exc().splitlines():
            log("  " + line)
        return 1
    finally:
        log.close()


if __name__ == "__main__":
    sys.exit(main())
